### ISSUE TITLE
Request for easier upgrade (When many IPTV-bundles are being used)

### ISSUE THREAD

**Issue by godztian** [Cigaras/IPTV.bundle#101]
I'm hosting some IPTV channels through Plex for some family and friends. I dont have any other bundles, except a bunch of IPTV-bundles. The reason I have several IPTV-bundels is that I want to keep the number of levels at a minimum. For example I have one bundle called IPTV-News.bundle, and another one called IPTV-Norway.bundle. (In addition to Spain National, Spain Regional, Bulgaria among others).

My request is a way to upgrade these bundles in an easier way (If possible). I cant simply replace the content of the folders. I have to update Info.plist, __init__.py, and icon-default and playlist.m3u.

One way could be to put all the config from __init__py to another script or file, like the m3u_parser and xmltv_parser scripts. this could be called Config.py, and be imported/included in __init__.py. In this file I could specify a custom icon, custom playlist etc, so that I could simply extract and overwrite all the files inside the bundle-folder, except the Config.py. Then the only file I had to modify would be Info.plist.

Any other solutions would be welcome as well :)

Thanks in advance for any input! (And thanks for this awesome bundle!)

**Comment by Weszzz** [comment]
Seems like you're using this same plugin multiple times because you want to group the channels together, isn't it?
My opinion on this is that it would be better to group the channels together.
This way you will have one app, but within the app you can select what channels you would like to watch.
Something like this GSE IPTV app does:
http://ndl.mgccw.com/mu3/app/20150905/19/1441460160871/ss/1_small.png

Let me know how u think about that! :)

**Comment by godztian** [comment]
Hi,

That is the way I had it in the beginning. But because I only had one bundle (The IPTV bundle), that was an extra step to click through. I'd like the number of levels between the Plex home screen, and the channel I want to watch as low as possible (A shallow structure instead of a deep structure if that makes sense).

I accept that the developers won't implement it, as I might be the only one with this specific need :)

**Comment by Weszzz** [comment]
@godztian 
Here you go: https://github.com/Weszzz/IPTV-Bundle-Customizer

**Comment by godztian** [comment]
Hi. Thanks for the script! Im sure it works, but how do I run a PHP-script on a windows machine?

I guess I can create a similar script in powershell as well :)

Thanksfor the effort!
