### ISSUE TITLE
LG WebOS not working

### ISSUE THREAD

**Issue by hydrouk** [Cigaras/IPTV.bundle#104]
I get absolutely no video/audio at all using the chrome browser on the TV or using the Plex app.  The channels play fine in a browser on my server.

I also noticed channel groups don't seem to be treated correctly like they do on SmartIPTV, i just get one massive list of all the available streams.

Any ideas? Thanks

**Comment by Cigaras** [comment]
Show us Your playlist.

**Comment by OneLoveAmaru** [comment]
Smart IPTV is an app in the LG Store that you can plug in an m3u to and it'll play those channels.

Both of my LG TVs work with Smart IPTV but not with your Plex plugin. I believe I'm on WebOS 3 now though.  All of the ts streams I use are H.264 so i wouldn't think they would need to be transcoded. Is there a way to force transcoding on the Plex side?

**Comment by OneLoveAmaru** [comment]
Once I disabled Direct Play/Stream in the LG app, I was able to stream it and confirmed the Plex server was transcoding while doing it.

You the man, thanks!

**Comment by Domoteek** [comment]
Work fine !! but video must be in m3u8 not in ts
