### ISSUE TITLE
Playlist only loads 41 of 1600 items

### ISSUE THREAD

**Issue by acs-ferreira** [Cigaras/IPTV.bundle#105]
I have a playlist (distant URL) with more than 1600 items.

But only 41 of them appears on the plugin.

How can i solve this?

Playlist loads correctly on SmartTV or VLC.

Link type is ` http://my.iptv.server/get.php?type=m3u&output=m3u8`

Thanks.

**Comment by Cigaras** [comment]
Click 41st item, it should load next 40 items then.

**Comment by acs-ferreira** [comment]
No, if i click the item it plays it :)

I have a "**More...**" button, but it loads the same items.
![image](https://cloud.githubusercontent.com/assets/12234510/24968517/c0095c4c-1fad-11e7-82b5-4f98f857ff6e.png)

**Comment by Cigaras** [comment]
I can't reproduce this it, when I click More... I get next 40 items. Could You sahre Your playlist? Also are You sure You are using latest Server version Version 1.5.4.xxxx and plug-in version [2.0.5](https://github.com/Cigaras/IPTV.bundle/releases)?

**Comment by acs-ferreira** [comment]
Yes, latest version of Plex and Plugin.

Original playlist can't be shared as logins are included on the Playlist items, sorry.
I've edited only that parts so items will not play, but the Playlist format is the same.

Find it here: [IPTV.zip](https://github.com/Cigaras/IPTV.bundle/files/917388/IPTV.zip)

**Comment by acs-ferreira** [comment]
Ok, i've reinstalled the Plugin and it seem to be fine now, thanks :)
