### ISSUE TITLE
Android iptv not loading

### ISSUE THREAD

**Issue by Acceptu** [Cigaras/IPTV.bundle#107]
[com.plexapp.plugins.iptv.txt](https://github.com/Cigaras/IPTV.bundle/files/919415/com.plexapp.plugins.iptv.txt)

Hello
I've been trying to get channels working on android and other devices for a while now

I've read through the trouble shooting guide with no luck and cant see any errors in the log

it work on the pc but not android, firestick and other devices

please can you take a look?

**Comment by Cigaras** [comment]
Sorry I can not help You with that, it is Plex issue, some streams work and some do not, all the information I have is listed in [Troubeshooting wiki](https://github.com/Cigaras/IPTV.bundle/wiki/Troubleshooting).
