### ISSUE TITLE
PS4 no image, but with sound 

### ISSUE THREAD

**Issue by dealpt** [Cigaras/IPTV.bundle#109]
Hello,

don't know if anyone can help me, but I managed to configure the plugin with a playlist that works perfectly fine within the VLC Player and Plex Chrome Player (on my laptop).
However, when streaming the channels to PS4 Plex Player I only get the sound, and the screen remains black.
Any idea?

**Comment by absentio** [comment]
I've got the same problem here.

**Comment by mp3il** [comment]
same

**Comment by Acceptu** [comment]
both ts and m2u8?

**Comment by mp3il** [comment]
Yes, it's all .ts inside a m3u8 playlist.

Sound, no image, had to disable direct stream / play on the ps4 plex app to get it with sound no image.
:(

**Comment by mp3il** [comment]
maybe it's something we can change in the plex transcoder?

**Comment by Acceptu** [comment]
I have Three solutions that seem to work for some people which are 
1. look for a mode setting and if it says mobile change it to TV
2. Look for direct play settings and change it to the opposite of what it is on
3. Check if you can Update the plex App

**Comment by mp3il** [comment]
1. in the Plex APP on ps4? or server? not sure what u are talking about :(
2. to keep direct play on?
3. its updated, checkeid on first

**Comment by mp3il** [comment]
OK! After digging, I found the solution in the Plex settings on PS4,

What worked for me was opening settings, going to video settings and setting to:

Local quality, Remote quality, online quality - all of them to **Original**

Allow direct play - Untick, leave it off
Allow direct stream - Keep it on, tick it.

Good luck !!!
