### ISSUE TITLE
Plex Media Scanner

### ISSUE THREAD

**Issue by hedgehog08** [Cigaras/IPTV.bundle#110]
Hello,

I have xpenology version DSM 5.2-5644 Update 5 and I have a Plex process called Plex Media Scanner that run multiple since I have the ITPV plugin and it takes all my processor performance. Do you know if it's normal or not?

**Comment by Cigaras** [comment]
Sorry, no idea, plug-in does not incorporate or initiate any scanners.

**Comment by KingKoopa08** [comment]
This isn't happening with mine and I have been running this plugin for a while. The plex scanner you might want to adjust the frequency it checks for new media files in settings.
