### ISSUE TITLE
Direct access to the TV channel

### ISSUE THREAD

**Issue by YoannZ** [Cigaras/IPTV.bundle#111]
Hello everyone I would like to remove the intermediate party when this connects to a television.

For example I would like that when I click on the television I want (See image 1) I fall directly on the channel without going through the image 2

Thanks you very much

**Image 1**
<a target="_blank" href="https://imageshack.com/i/po9aCPaEj"><img src="http://imagizer.imageshack.us/v2/xq90/924/9aCPaE.jpg" border="0"></a>

**Image 2**
<a target="_blank" href="https://imageshack.com/i/pnISGs8oj"><img src="http://imagizer.imageshack.us/v2/xq90/923/ISGs8o.jpg" border="0"></a>

**Comment by Cigaras** [comment]
This was already discussed in #102 with no clear resolution, looks like that is how Plex player is ment to work.

**Comment by YoannZ** [comment]
Ok thanks for the answer sir ;)
