### ISSUE TITLE
Put a description on a TV channel

### ISSUE THREAD

**Issue by YoannZ** [Cigaras/IPTV.bundle#112]
Hello everyone here I would like to be able to put a description below the string via the .m3u list for example to add tvg-description = "The description of the TV".

Can you help me here is an image or I would like it to show, I know it is doable but I do not know too much how I tested a lot of code in python but nothing works.

<a target="_blank" href="https://imageshack.com/i/pnsBmMR9j"><img src="http://imagizer.imageshack.us/v2/xq90/923/sBmMR9.jpg" border="0"></a>

**Comment by Cigaras** [comment]
Plex API is very limited and description is used to display [program guide](https://us.v-cdn.net/6025034/uploads/editor/lb/1eu2vioyp2lq.png) when available, but if program guide is not available there should be text "[No description available](https://github.com/Cigaras/IPTV.bundle/blob/master/Contents/Code/__init__.py#L194)" that is absent in Your screenshot, so it is quite likely that it is not possible to add anything in this place.

**Comment by YoannZ** [comment]
So I would need to put one more line in my .m3u file?

As for example tvg-description = "The description"?

**Comment by YoannZ** [comment]
Thanks it's now resolved
