### ISSUE TITLE
Create subfolders

### ISSUE THREAD

**Issue by YoannZ** [Cigaras/IPTV.bundle#113]
Hello I would like to know how to create subfolders to search more easily.

Thank you

**Comment by Cigaras** [comment]
Use [`group-title`](https://github.com/Cigaras/IPTV.bundle/wiki/Playlist#attributes) attribute.

**Comment by YoannZ** [comment]
Ok thanks i'm gona work on it.
I need to do a folder in other folder.

If i have a solution i gona share with comunity.
Thanks :)
