### ISSUE TITLE
Retrieve the ip address of the person who logs in

### ISSUE THREAD

**Issue by YoannZ** [Cigaras/IPTV.bundle#115]
Hello, all is in the title.
I would like to retrieve the ip address of the person who connects it in order to stop it in database to be able to subsequently make a thorough analysis.

Thank you

**Comment by Cigaras** [comment]
This does not look like a question related to this particular plug-in, if You are trying to rewrite my plug-in to Your personal needs I think [Plex Channel Development forum](https://forums.plex.tv/categories/channel-development) would be a better place to learn Plex API capabilities.
