### ISSUE TITLE
New line in the description

### ISSUE THREAD

**Issue by YoannZ** [Cigaras/IPTV.bundle#117]
Hello I would like to know how to skip a line in the description?

Thank you very much

**Comment by Cigaras** [comment]
Not sure what You mean by "description". Plex VideoClipObject description is called summary as is used to display program guide. In M3U playlist comments start with # symbol and those lines except #EXTINF are ignored.

**Comment by YoannZ** [comment]
Thanks to answer.
Then i need to return a line in the summary.
Ex: 
Hi, how are you today?

I wanna to see

Hi, 
How are you today?

If it's ont html it's be like 
Hi, </br>how are you today?

But in plex how to do that?

**Comment by YoannZ** [comment]
Is like the "< / br>"

**Comment by Cigaras** [comment]
[Again](https://github.com/Cigaras/IPTV.bundle/issues/115) You are asking question not about this particular plug-in but about Plex plug-ins framework or even Python in general, and again You should check [Plex Channel Development forum](https://forums.plex.tv/categories/channel-development).

Answer to Your question would be [`\n`](http://stackoverflow.com/questions/11497376/how-would-i-specify-a-new-line-in-python).

**Comment by KingKoopa08** [comment]
Yoannz you really need to start looking into paying someone with all the time you are taking for these requests that you have the tools to the answers. Cigaras built this awesome plugin and isn't asking anything in return so please keep that in mind with all your requests.

**Comment by YoannZ** [comment]
Sir if i ask some help i'ts because i simple \n it's not working on iOS platform but, ok i don't ask help anymore 😉

**Comment by Cigaras** [comment]
In some case Plex deliberately ignores new line symbols and spills out all the text in single line, or adds an empty line in between:
<img src="https://cloud.githubusercontent.com/assets/244432/25848056/5e7776ac-34c1-11e7-9569-ec6b345e879a.png" width="49%"/> <img src="https://cloud.githubusercontent.com/assets/244432/25848061/62aaff5a-34c1-11e7-83b8-740342187821.png" width="49%"/>
I guess iOS player is one of these cases and plug-in has no control over it.
