### ISSUE TITLE
A lot of Connection Losts....Buffering Problem

### ISSUE THREAD

**Issue by thomy22** [Cigaras/IPTV.bundle#118]
On VLC with a great Buffer (5000ms) the Streams works perfect! Can i make a Buffering on your Tool with a special Code on the m3u List? On the Preferences i can´t set :-(

I Hope we can Fix this Issue.  The Streams works Top on VLC.

**Comment by YoannZ** [comment]
I have the same problem, if you know issue let me know please ;)

**Comment by Cigaras** [comment]
Only buffer setting I know is in Server Settings -> Server -> Transcoder -> Transcoder default throttle buffer, not sure if it is related. Google search also suggests to check players [Preferences -> System -> Cache](https://forums.plex.tv/discussion/48635/increase-client-buffer)

**Comment by thomy22** [comment]
The Streams always plays on "Direct Play" no transcoding needed. I look i can Transcode every stream and stream it myself.

I look on Cache setting, but not every App work with this.

**Comment by Cigaras** [comment]
Would anyone mind sharing a sample stream to test it?

**Comment by thomy22** [comment]
i send you 2 links on pm in the Plex Forum....you can test it

**Comment by Cigaras** [comment]
The streams I found in my Plex inbox do not work.
