### ISSUE TITLE
How to see logs?

### ISSUE THREAD

**Issue by FezVrasta** [Cigaras/IPTV.bundle#119]
> Provided playlist files are invalid, missing or empty, check the log file for more information

I have the Plex logs enabled (set to verbose) but when I read them I can't find anything related to the m3u URL not working.

Are the IPTV.bundle logs saved somewhere else?

**Comment by FezVrasta** [comment]
here
https://github.com/Cigaras/IPTV.bundle/wiki/Troubleshooting

**Comment by KingKoopa08** [comment]
Here you go.

C:\Users\Administrator\AppData\Local\Plex Media Server\Logs\PMS Plugin Logs
