### ISSUE TITLE
Stuck at "Playlist is reloading in the background, please wait"

### ISSUE THREAD

**Issue by Salvasdf** [Cigaras/IPTV.bundle#122]
After adding URL Playlists (semicolon separated) the plugin goes to reloading, and now it shows : "Playlist is reloading in the background, please wait" everytime, and nothing refreshes.

I did delete the plugin (in plug-ins folder, cant manually in the plex channels options), reinstall and same problem, also removing the URL playlist, it seems like the plugin is stuck indefinitely.

Btw: Plex is running in Ubuntu, x64

**Comment by Cigaras** [comment]
Can You show me playlist You are using?

**Comment by andruxnet** [comment]
I installed version 2.1.1 and same thing, I have emailed you the playlist urls I have been trying.

**Comment by Salvasdf** [comment]
I had to remove all IPTV Content from Plex folder (By `find -type f -name '*IPTV*' -delete` ), then reinstall. Now works like a charm.

Btw, Now I'm not using the same Playlist, maybe there was a problem with one of them.

**Comment by andruxnet** [comment]
You mean from the plug-ins folder?

**Comment by Salvasdf** [comment]
Yes

**Comment by andruxnet** [comment]
Still nothing, maybe it is the channel that has the problem.

**Comment by Cigaras** [comment]
@andruxnet Your playlist peliculas.m3u has symbols on line 3395 in group-title attribute that Plex can't handle.
