### ISSUE TITLE
I have a simple question about logos

### ISSUE THREAD

**Issue by RStoroy** [Cigaras/IPTV.bundle#131]
Where to place channel logo? Example channel name "SE: BBC Earth HD" <- This name can't be changed. I've tried to name the logo SE: BBC Earth HD.png and placed it in the resource folder of plugin. PROBLEM: You can't use  : colon in the filename. Is there a way to fix this?

**Comment by Cigaras** [comment]
Use M3U EXTINF attribute [logo](https://github.com/Cigaras/IPTV.bundle/wiki/Playlist#attributes) or [tvg-logo](https://github.com/Cigaras/IPTV.bundle/wiki/Playlist#attributes), like this:
```
#EXTM3U
#EXTINF:0 logo="SE BBC Earth HD.png",SE: BBC Earth HD
http://www.stream-url.com

```
