### ISSUE TITLE
Can duplicate plugin ? (only one work at the same time)

### ISSUE THREAD

**Issue by Domoteek** [Cigaras/IPTV.bundle#132]
Hello, thank you for the big update of your plugin !!

I tried to duplicate this plugin. 
work but when one user open the first plugin and launch flux . no problem.
when a second plugin launch the first close, and when reload the first stream a second stop..

what do i do for launch many time this plug in ?

**Comment by Cigaras** [comment]
If You made plug-ins copy as described in the [wiki](https://github.com/Cigaras/IPTV.bundle/wiki/How-to-install-IPTV.bundle-multiple-times) then plug-ins themselves should work fine, check both [logs](https://github.com/Cigaras/IPTV.bundle/wiki/Troubleshooting), they should be named as set in [Info.plist](https://github.com/Cigaras/IPTV.bundle/blob/master/Contents/Info.plist#L6) file. If You did not use the guide, then plug-ins will collide and won't work.

However, it is likely that Your provider does not allow You to watch multiple streams at a time as in issue #67, can you watch multiple streams with VLC?

**Comment by Domoteek** [comment]
Helo!

yes it's easy to duplicate plugin. i do same the wiki.

yes it's my own xtream i can have 100 connexion. 

Now i try to change line  login/password  and i test.
