### ISSUE TITLE
can not convert below 103kbps

### ISSUE THREAD

**Issue by knuckledude** [Cigaras/IPTV.bundle#135]
PMS Version 1.7.5.4035 returns this response on my old NEC monitor other clients play fine I believe this is related to this bug https://forums.plex.tv/discussion/266619/bandwidth-error-started-with-pms-1-5-3-seems-to-be-tv-specific

**Comment by privatesam** [comment]
Same issue here

**Comment by FezVrasta** [comment]
I have the same issue. Can't find  a way to fix it

**Comment by knuckledude** [comment]
roll it back was the only fix that I could find

**Comment by FezVrasta** [comment]
I tried to install plex media server 1.4 but I still get the error 🙁

**Comment by knuckledude** [comment]
What device and display are you watching on ? If you read the link in my OP there are/were 2 different problems with the same symptom -- one was due to the latest update ( which was fixed for me by rolling it back ) and one that started on earlier releases using certain displays -- so TV A had the issue but move the player to TV B and it played fine

**Comment by FezVrasta** [comment]
A Chromecast first gen

**Comment by GoNotCougsWA** [comment]
Turn off direct or direct stream that fixed it for me

**Comment by chasgames** [comment]
Settings -> playback -> internet streaming -> Original -> Save changes

**Comment by FezVrasta** [comment]
I tried this already
