### ISSUE TITLE
Bug with picking up tvg-logo=".....HD.png" in m3u

### ISSUE THREAD

**Issue by lolento** [Cigaras/IPTV.bundle#136]
Hello,

Just started using this on my plex server.  Found a weird bug with picking up channel logos.

I find if the Channel logo ends with [space]HD.png on the m3u file, the logo is not going to be picked up.  And it will not try to search for the same logo in the experimental path in settings.

However, if I remove all tvg-logo="" entries, and just let it search the experimental path, then the same logo is found.

**Comment by Cigaras** [comment]
Would You mind sharing Your playlist or at least a fragment with mentioned issue?

**Comment by lolento** [comment]
#EXTINF:0 tvg-id="UK: 3E SD" tvg-logo="http://192.168.2.118/Plex-Logos/3E HD.png" tvg-name="3E HD",3E HD
http://stream.fabiptv.com:25461/live/email/password/1237.m3u8
#EXTINF:0 tvg-id="UK: 4SEVEN SD" tvg-logo="http://192.168.2.118/Plex-Logos/4Seven SD.png" tvg-name="4Seven SD",4Seven SD
http://stream.fabiptv.com:25461/live/hilman.chung@gmail.com/flawlesssucks/1238.m3u8

In example, "3E HD.png" does not get picked up in the Plex Channel but "4Seven SD.png" does.  And if I change "3E HD.png" to "3E_HD.png" and create the same file in the Plex-Logos folder, it gets picked up.

And if I just leave out the tvg-logo="..." line altogether, and just set a path under IPTV Channel settings, the "3E HD.png" logo gets picked up.

**Comment by Cigaras** [comment]
This is strange. Does issue repeats if You put logos directly into Resources folder without using the path `http://192.168.2.118/Plex-Logos/`? I also would like to see both files `3E HD.png` and `4Seven SD.png` because I can not reproduce this by changing names of ones I have.

**Comment by lolento** [comment]
Yes, if I remove the URL, the logos are picked up just fine.

https://www.dropbox.com/s/f41ug48hw8ysp1l/3E%20HD.png?dl=0

https://www.dropbox.com/s/n7slhy0zkj0gxt7/4Seven%20SD.png?dl=0

**Comment by Cigaras** [comment]
What if You change space to %20 in URL, so Your playlist looks like this:
```
#EXTINF:0 tvg-id="UK: 3E SD" tvg-logo="http://192.168.2.118/Plex-Logos/3E HD.png" tvg-name="3E HD",3E HD
http://stream.fabiptv.com:25461/live/email/password/1237.m3u8
#EXTINF:0 tvg-id="UK: 4SEVEN SD" tvg-logo="http://192.168.2.118/Plex-Logos/4Seven SD.png" tvg-name="4Seven SD",4Seven SD
http://stream.fabiptv.com:25461/live/email/password/1238.m3u8
```

**Comment by lolento** [comment]
Yup, you're right.  Adding %20 works.

The way I was doing it was I was using a script to add an URL in front of the channel name to get all the tvg-logo populated....
