### ISSUE TITLE
Simple bandwidth question

### ISSUE THREAD

**Issue by hyperexpert** [Cigaras/IPTV.bundle#137]
When using this plugin with my m3u8 list, lets say I have a bunch of http://website.com/file.ts links, when I play one, does it stream the link to me directly from the source to my plex client bypassing my plex server? or does it actually download to plex server and then plex processes it and stream it to me?

**Comment by Cigaras** [comment]
Depends on [Direct Play, Direct Stream and Transcoding settings](https://support.plex.tv/hc/en-us/sections/200076783-Direct-Play-Direct-Stream-Transcoding), plug-in itself does not handle the playback at all, but it can set different flags for Plex to know what to do like [Optimized for streaming option](https://github.com/Cigaras/IPTV.bundle/wiki/Preferences) or [optimized_for_streaming attribute](https://forums.plex.tv/discussion/comment/1379420/#Comment_1379420), however I can not guaranty that all Plex clients will pay attention to them.
