### ISSUE TITLE
Not showing up as a channel

### ISSUE THREAD

**Issue by hutchy1990** [Cigaras/IPTV.bundle#14]
I done everything in the install instructions but it is not showing up in plex channels this app doesnt show up :S

**Comment by Cigaras** [comment]
It's not the plugins issue, You did something wrong [installing](https://github.com/Cigaras/IPTV.bundle/blob/master/README.md#installation) it, please refer to Plex support with Plex issues: [Why isn’t the channel bundle I installed showing up in Plex?](https://support.plex.tv/hc/en-us/articles/201187666-Why-isn-t-the-channel-bundle-I-installed-showing-up-in-Plex-).

**Comment by Cigaras** [comment]
To change the menu edit the [playlist.m3u](https://github.com/Cigaras/IPTV.bundle#playlist-structure-and-examples) file, as for TV guide, there is [no support for that](https://github.com/Cigaras/IPTV.bundle#to-do-list) at the moment.

**Comment by hutchy1990** [comment]
I know I ment the menu as in list channels instead of have them in a folder style there are some tutorials how to make TV guides in Python so I may give it a shot to learn a new language :)

**Comment by hutchy1990** [comment]
Also can I ask you see in playlist.m3u how do you add a description

**Comment by Cigaras** [comment]
All the available m3u attributes are described in [readme file](https://github.com/Cigaras/IPTV.bundle#playlist-structure-and-examples), and description I was planning on using for TV guide, would be the easiest way to display current and upcoming shows

**Comment by hutchy1990** [comment]
Ok man just to say this is a bril app I think plexrpi looks so much nicer than xbmc so if this iptv app only had a menu I would cancel my virgin media and use this so I have started learning how to do a menu and change Chanel while watching a show with page up and page down then lastly I will add record will I send you the code when I am done?

**Comment by Cigaras** [comment]
It's hard to understand what You just wrote, but sure, go for it.
