### ISSUE TITLE
View style of the playlist

### ISSUE THREAD

**Issue by ale86ch** [Cigaras/IPTV.bundle#140]
Hi,

I'm using the web browser to see my items in Plex, also for watching the TV with your Plug-in. I'd like to see the items of the playlist with the List style but if I close the browser and get back in or I click on "More..." to go to the next channels it goes back to the "Details" view style. Is there a way to fix this? Is it caused by the plugin of is it Plex?

**Comment by Cigaras** [comment]
Plug-in does not touch listing settings, it is all managed by Plex so it is definitely Plex issue. However it is possible that maybe I can do something about it, but I do not have time for it at the moment :frowning:
