### ISSUE TITLE
iptv stream doesn't work over the internet

### ISSUE THREAD

**Issue by entei1337** [Cigaras/IPTV.bundle#146]
Hi, i have a m3u with some live Streams from my e2 receiver.

example content of the m3u:
#EXTM3U 
#EXTVLCOPT--http-reconnect=true
#EXTINF:-1,Sat 1 HD
http://xyzserver:11112/1:0:19:EF74:3F9:1:C00000:0:0:0:?bitrate=3000000?width=1280?height=720?aspectratio=2?interlaced=0?framerate=29.97

when i start the streams over VLC player local and over internet it work fine.
when i start the strem over Plex iptv.bundle it work only in local network on a windows 10 computer.
public m3u8 streams works fine too over the internet...

The Problem: when i start my stream over internet with any Plex clients it won't work. i tryed everything. The normal movies and series works fine.

I thing the clients want to transcode my stream, but its alleredy transcoded by the source e2 receiver.

what can i change to make it work?

codec of streams: 
A: aac lc,48000, stereo, 130 kb/s
V: h264 main L3.1, yuv 420p, 1280x720
Plex Server Version: Version 1.8.1.4139 on a qnap ts451+
newest iptv.bundle
internet connection 100mbit upload, ports opened

**Comment by entei1337** [comment]
Plex Server Version: Version 1.8.1.4139 on a qnap ts451+
newest iptv.bundle

**Comment by Cigaras** [comment]
I have no idea what to suggest You. If You thinks it is transcoding issue try disabling it by enabling [Direct Play and Direct Stream](https://support.plex.tv/hc/en-us/articles/200250387-Streaming-Media-Direct-Play-and-Direct-Stream) in client or enabling [Optimized for streaming](https://github.com/Cigaras/IPTV.bundle/wiki/Preferences) in plug-in.
