### ISSUE TITLE
 Sending UDPXY extra parameters in the URL

### ISSUE THREAD

**Issue by LERT956** [Cigaras/IPTV.bundle#152]
I am trying to watch a usp channel using the udprxy program.

If I load the playlist in VLC, it works fine.

`http://192.168.111.139:4088/udp/239.0.0.77:8208`

the udpxy shows the destination as:

`239.0.0.77:8208`

And I can see the stream perfectly.  But using the IPTV plugin, when trying use the same playlist, the udpxy gives this as destination:

`
239.0.0.77:8208?autoAdjustQuality=0&hasMDE=1&location=lan&mediaBufferSize=16384&X-Plex-Client-Identifier=df95400e7f83000c-com-plexapp-android&X-Plex-Supported-Commands=abort&X-Plex-Token=jNGZGXpUKakirArBppCK`

Is there a way not to send that extra information to de udpxy?

Thanks

**Comment by Cigaras** [comment]
I can not reproduce it.

I have udpxy running on my Asus router with Merlins [firmware](https://asuswrt.lostrealm.ca/), I play a stream on Plex Web and in udpxy status screen I see correct destination, please add more information about Your setup, and if possible share a fragment of Your playlist.
