### ISSUE TITLE
.ts .m3u8 streams not responding on Internet Browser

### ISSUE THREAD

**Issue by VilDegard** [Cigaras/IPTV.bundle#153]
Hi,

I have a playlist.m3u and I've changed the URLs extensions .ts to .m3u8 as indicated in previous posts. 
However, once the playlist is charged, I can't read any streams on any browsers (Firefox, Safari, EDGE...) but when I go on my Plex app on iOS I can read them with no problems. 

Here are the flux info:

Media

Container MPEGTS
Web Optimized No
Protocol hls
Indirect true
Part

Container MPEGTS
Web Optimized No
Codec H264
Codec AAC

Any help is welcome.
Thanks in advance.
V.

**Comment by Cigaras** [comment]
What's a "flux"?

**Comment by VilDegard** [comment]
Hi Cigaras,

I meant "video stream".
Whatever URL I pick (changed extension from .ts to .m3u8, same results) that contains a video stream can't be read on any browsers.

Thanks in advance for your help.

**Comment by WolfganP** [comment]
Same here, I was never able to make the plugin work in my browser or TV's Plex app (same stream works OK with VLC or other IPTV apps in the SmartTV, no transcoding is ever needed)...

**Comment by Cigaras** [comment]
Any sample stream I could try?

**Comment by VilDegard** [comment]
@Cigaras I have a 12 months IPTV subscription with personal codes. I'm afraid I can't take the risk to transfer it. 
However I can manage to get the exact streams for 24h. 
Please send me your email address in a private message that way I can send you the playlist. 

Thanks

**Comment by Cigaras** [comment]
cigaras@gmail.com

**Comment by WolfganP** [comment]
Update: I updated to plugin v2017-08-07 via UAS and used the NASA TV stream as test and it worked OK. Thx!

#EXTINF:0 tvg-id="NASATV.us" group-title="PEK IPTVlinks", NASA TV
https://nasa-i.akamaihd.net/hls/live/253565/NASA-NTV1-Public/master_2000.m3u8

**Comment by VilDegard** [comment]
Still not working for me... 
@Cigaras have you had time to check the playlist I sent you?

**Comment by Cigaras** [comment]
Sorry @VilDegard I did not have time to check it and looks like the link is no longer valid. There is a big change that if You give me a new link that dies in 24 hours I wont be able to check it again ☹️.
