### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by joaoescribano** [Cigaras/IPTV.bundle#155]
Hello folks, i've tried to change the UI of the plugin cuz it sucks.... sorry, but it's true... it's treeible to navigate.... the EPG doesn't works well and we cant see a "program grid"...

But looking trought the code, i got many difficults to understand how the plugin creates pages... (i've never developed to Plex before).

Anyone have tried this before? or just share this feeling about the plugin UI?

**Comment by Cigaras** [comment]
UI is done by Plex, not the plug-in.

**Comment by joaoescribano** [comment]
Damm... so there is no way to change the UI???

Even using OpenPHT?

**Comment by Cigaras** [comment]
You can change the UI, but You need to change the clients UI, not the plug-ins, because plug-in does not have its own UI, it's a server plug-in, it just takes information from a `m3u` file and puts it into Plex [`DirectoryObject`](https://us.v-cdn.net/6025034/uploads/editor/rg/jxvpxxxt63r6.pdf).

**Comment by joaoescribano** [comment]
But only with custom made plex player, right?

Like OpenPHT that is opensource, cuz plex web/android/ps4/tizen/etc.... we could never change a line of it :/

**Comment by Cigaras** [comment]
Well, You can always apply for a [job at Plex](https://www.plex.tv/about/careers/) and then You should have access to their closed code 😄

**Comment by joaoescribano** [comment]
Thanks dude, I've never think about it... wooooooooooooowwwww
