### ISSUE TITLE
No video playback

### ISSUE THREAD

**Issue by vdias** [Cigaras/IPTV.bundle#169]
Trying to play a stream from my local udpxy... list loaded correctly on plugin but no video playback.

List works without any problems with VLC.

[com.plexapp.plugins.iptv.log](https://github.com/Cigaras/IPTV.bundle/files/1629762/com.plexapp.plugins.iptv.log)

**Comment by Cigaras** [comment]
Theere are no errors in attached log, please see [Troubleshooting](https://github.com/Cigaras/IPTV.bundle/wiki/Troubleshooting) part of the wiki, there is nothing else I can suggest You.
