### ISSUE TITLE
EPG

### ISSUE THREAD

**Issue by hutchy1990** [Cigaras/IPTV.bundle#17]
I am wanting an EPG for this app I have given it a shot but failed I will pay if someone can code this for me and then release it on this project I just need it that much that I am willing to pay

**Comment by Cigaras** [comment]
EPG is available (kind of) in version 1.1.0, more info in the [readme file](https://github.com/Cigaras/IPTV.bundle#program-guide) and [forum](http://forums.plex.tv/discussion/comment/1152230/#Comment_1152230).
