### ISSUE TITLE
New Plex iOS

### ISSUE THREAD

**Issue by benpower85** [Cigaras/IPTV.bundle#18]
Hi, love the work you guys have done. Really appreciate the time and effort spent and always happy to donate.

I am having an issue with the IPTV app in the new iOS version of plex. Before I updated to 4.0 it was working perfectly. Now the channels are showing up within the channel, but when I press it to load it just continues to spin.

I have contacted plex and the dev team wrote;

Sorry, but we can't provide support for third-party channels. You'll need to contact the developer of that channel for support.

So here I am. Any chance you could look in to this for us?

Thank you

**Comment by benpower85** [comment]
Plex have just come back with this updated response;

We have tested various supported channels, and these all work as expected, but we can't possibly test every third-party channel that's out there  If the channel developer gets in touch & requests assistance, we'll happily help him/her figure out what's causing the compatibility issue, however we simply don't have the staff to provide end-user support for things we didn't create - I hope you can appreciate that.

**Comment by Cigaras** [comment]
I'd love to help, but I do not have any Apple devices, also I no longer use Plex, I switched to Kodi because it already has a much better [IPTV plugin](http://kodi.wiki/view/Add-on:IPTV_Simple_Client) than I did, and it suits me better in other aspects also, like [launching external apps](http://kodi.wiki/view/Add-on:Advanced_Launcher) for example, So I will tinker with this from time to time, but as I no longer use it is hard to find enough motivation especially when I can not test it with devices I do not have and dev.plexapp.com is no more.

**Comment by benpower85** [comment]
Thanks for coming back to me. It's a shame that you have decided to go down the kodi route. Plex has just started to allow channel sharing and I was looking to use your channel to help watch TV around my house where I don't/can't have aerials. I've tried kodi but on android boxes it wasn't as nice as plex. You were the only channel out there that did this.

Good luck!

**Comment by benpower85** [comment]
@Cigaras 

Sorry to be a pain again. Is there any way of adding more than one copy of your channel on a single server and renaming the channel from just IPTV? Or is it strictly one per server?

I know we can change the main icons/images but can't work out how to rename or duplicate.

**Comment by Cigaras** [comment]
Why would you need a duplicate, just group stuff the way You want by using [group-title attribute](https://github.com/Cigaras/IPTV.bundle#playlist-structure-and-examples).

But if You really need that, just rename the folder to NEWNAME.bundle and then change TITLE and PREFIX variables in __init__.py file lines [17 and 18](https://github.com/Cigaras/IPTV.bundle/blob/master/Contents/Code/__init__.py#L17-L18), from
```
TITLE = 'IPTV'
PREFIX = '/video/iptv'
```
to
```
TITLE = 'NEWNAME'
PREFIX = '/video/newname'
```
