### ISSUE TITLE
Epg timeline on smart tv is not in order.

### ISSUE THREAD

**Issue by bokiroki** [Cigaras/IPTV.bundle#186]
so epg when is displayed on tv looks like this, it's not in order.
![30121939_10216194203512315_1509584432_o](https://user-images.githubusercontent.com/19166918/38363247-39c3b222-38d4-11e8-89e1-e19a60702af8.jpg)

when i open plex plugin in chrome everything is in order
![untitled](https://user-images.githubusercontent.com/19166918/38363273-5b0ce66a-38d4-11e8-99d0-54886f9aa655.png)

also is there a way to expand epg on samsung smart tv, like i can do on chrome
thanks..

**Comment by Cigaras** [comment]
That's Plex clients/players issue and there is nothing I can do about it.

To be honest, I wouldn't call it an issue, everything is in order, just displayed in single line instead of a column.
