### ISSUE TITLE
HTTP referer/referrer

### ISSUE THREAD

**Issue by HarryElSuzio** [Cigaras/IPTV.bundle#187]
Hello, it would be possible to add one more line to add to the channels besides the user agen the referrer
Here is an example of my channels in my list in vcl works perfect but I would like to put it in plex with your help
#EXTINF:-0 tvg-id="ID EPG" tvg-name="NAME " tvg-logo="URL IMG LOGO" group-title="Name Group",NAME CHANNEL
#EXTVLCOPT:http-referrer=URL REFERRER CHANNEL
#EXTVLCOPT:http-user-agent=USER AGENT REQUIRED
URL CHANNEL

**Comment by Cigaras** [comment]
I doubt that it will work as there is no mention of referrer in [documentation](https://us.v-cdn.net/6025034/uploads/editor/rg/jxvpxxxt63r6.pdf), could You give me a sample stream to test?

If no, then add a new line init.py file before line [297](https://github.com/Cigaras/IPTV.bundle/blob/master/Contents/Code/__init__.py#L297) yourself:
```    HTTP.Headers['Referer'] = 'some text'```
or
```    HTTP.Headers['Referrer'] = 'some text'```

so the whole PlayVideo function looks like this:
```
@indirect
@route(PREFIX + '/playvideo.m3u8')
def PlayVideo(url, c_user_agent = None):

    # Custom User-Agent string
    if c_user_agent:
        HTTP.Headers['User-Agent'] = c_user_agent

    HTTP.Headers['Referrer'] = 'some text'
    return IndirectResponse(VideoClipObject, key = url)
```

If this works, I'll add support for the #EXTVLCOPT:http-referrer directive.

**Comment by HarryElSuzio** [comment]
#EXTINF:-1 tvg-id="LA2 TDT SD 4.sp" tvg-name="LA 2" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/f/f3/Se15.png" group-title="TDT",LA 2 
#EXTVLCOPT:http-referrer=http://player.livesports.pw/la2/
#EXTVLCOPT:http-user-agent=Mozilla/5.0 (Windows NT 10.0; …) Gecko/20100101 Firefox/59.0
http://xxedge63.livesports.pw/live/la2/chunklist.m3u8?md5=8yn90WMN-_iKb6wOluHTYA&expires=1525777298




say that the channel that the test post will not last long, that they change very often but that today works and that in this way, that the structure perfectly

**Comment by HarryElSuzio** [comment]
I would say add something else because I did what I indicated and now it does not open or the plugin settings

**Comment by Cigaras** [comment]
I've made a new branch to test [referer|https://en.wikipedia.org/wiki/HTTP_referer] and referrer, I highly doubt that they will work, but either way, download the [zip file](https://github.com/Cigaras/IPTV.bundle/archive/referer.zip), extract it, rename from `IPTV.bundle-referer` to `IPTV.bundle`, copy to Your plug-ins folder and use playlist You mentioned [above](https://github.com/Cigaras/IPTV.bundle/issues/187#issuecomment-387031963).

**Comment by HarryElSuzio** [comment]
I'm sorry to say that I would never work for a global list as much for a single channel as it puts the referrer of the channel that I previously indicated but each channel has a different referrer

     HTTP.Headers ['Referer'] = 'http://player.livesports.pw/la2/'
     HTTP.Headers ['Referrer'] = 'http://player.livesports.pw/la2/'

these referer are only valid for a channel and even then I do not know if it would work if you want I can try it but it seems to me to throw away the time as I told you, that alone would be valid for a channel

**Comment by Cigaras** [comment]
I do not understand what are You saying.

If this works with single channel, I will update my plug-in so it takes referer from `#EXTVLCOPT:http-referrer` directive and then it will work with a whole list, but first I need to make sure it works with at least one channel.

**Comment by HarryElSuzio** [comment]
what I say and forgive because I use xd translator is that each channel uses a different referrer and within the code it seems impossible for me to directly target the referrer instead of a tool that interprets it

**Comment by Cigaras** [comment]
As I said, if it works with one channel, I will make a "tool that interprets it".

**Comment by HarryElSuzio** [comment]
ok I try and I'll tell you soon

**Comment by HarryElSuzio** [comment]
As you can see it is the same channel as the other time but it has changed its referrer

**Comment by Cigaras** [comment]
[Committed](https://github.com/Cigaras/IPTV.bundle/commit/e93a295a7d410284b9d9f272a77dac639ac5c9e7) a new version to test, please download [zip](https://github.com/Cigaras/IPTV.bundle/archive/referer.zip) and rename as instructed [above](https://github.com/Cigaras/IPTV.bundle/issues/187#issuecomment-391226233).

Please keep in mind that I did not test it myself, so if it breaks please check the [com.plexapp.plugins.iptv.log](https://github.com/Cigaras/IPTV.bundle/wiki/Troubleshooting) file.

**Comment by HarryElSuzio** [comment]
it does not work

**Comment by HarryElSuzio** [comment]
the first time with some text if it worked in local plex now no longer

**Comment by Cigaras** [comment]
User Agent string in Your [sample](https://github.com/Cigaras/IPTV.bundle/issues/187#issuecomment-391234296) has invalid character "…", Plex can't handle it...

**Comment by HarryElSuzio** [comment]
I had that error, I did not realize when it came to capturing the channel, it was working perfect, many thanks

**Comment by Cigaras** [comment]
Referer works?

**Comment by HarryElSuzio** [comment]
yes yes its perfec work

**Comment by HarryElSuzio** [comment]
https://lh3.googleusercontent.com/-VaL_9SiSgwY/WwUm8Eq3HKI/AAAAAAAAEZA/JxFoSnLSkkYwR5askthxCJVoec7BWWjHgCL0BGAYYCw/h1080/2018-05-23.png

https://lh3.googleusercontent.com/-ISgoXoswZRU/WwUkwY8U4iI/AAAAAAAAEY0/xykLPqOg5jIhNN24ZrytyNSwHkSrl3YmQCL0BGAYYCw/h1080/2018-05-23.png

I have tested several different channels with different referrer to corroborate the work and perfect

**Comment by leylayx** [comment]
This advance is great. I am very happy with the new version.
