### ISSUE TITLE
Is there support for something like --> group-logo !?

### ISSUE THREAD

**Issue by mike-pt** [Cigaras/IPTV.bundle#20]
If not please consider as a FR

**Comment by Cigaras** [comment]
OK, I added it to the [to-do list|https://github.com/Cigaras/IPTV.bundle#to-do-list], but it might take some time :)

**Comment by mike-pt** [comment]
thanks :)

**Comment by Cigaras** [comment]
Fixed, for more info read the [wiki](https://github.com/Cigaras/IPTV.bundle/wiki/Playlist-structure-and-examples#attributes)
