### ISSUE TITLE
Multiple installs

### ISSUE THREAD

**Issue by txt3rob** [Cigaras/IPTV.bundle#21]
Hi,

I noticed a plex server with multiple installs of this addon.

is there a guide or a file i need to change so i can do the same?

it's so i can have playlists for different stuff so it's easy to find.

**Comment by txt3rob** [comment]
i've worked it out now.

change directory name to something like IPTV2.bundle
alter info.plist

change 
```
<string>com.plexapp.plugins.IPTV</string>
```

to 

```
<string>com.plexapp.plugins.IPTV2</string>
```

edit __init__.py

Change

```
TITLE = 'IPTV'
```

to 

```
TITLE = 'IPTV2'
```

change

```
PREFIX = '/video/IPTV'
```

to

```
PREFIX = '/video/IPTV2'
```

and done :)

**Comment by Cigaras** [comment]
Good job mate :+1:

**Comment by txt3rob** [comment]
really handy as i have a good few playlists :)
