### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by obelix1502** [Cigaras/IPTV.bundle#215]
Hello,
Please, apologize me for my English.
When I try to install IPTV2.bundle from WebTools, I receive this : 
An error occured, please check the logs.

Errorinfo:
```
Requested URL: webtools2?module=git&function=getGit&url=https%3A%2F%2Fgithub.com%2FCigaras%2FIPTV.bundle&branch=
Error Code/Message: 500/Internal Server Error
```
Can you help me ?
Thanks.

**Comment by Cigaras** [comment]
No idea, that is WebTools error, not plug-ins, try installing [manually](https://support.plex.tv/articles/201187656-how-do-i-manually-install-a-plugin/).
