### ISSUE TITLE
Plugin dissapear

### ISSUE THREAD

**Issue by estebart** [Cigaras/IPTV.bundle#222]
the plugin disappeared from my plugin list.
I reinstall the app but plex does not detect it.
Any idea what the error might be?

Plex version 1.15.3.876 for windows

**Comment by estebart** [comment]
delete the iptv files contained in plug-in support and it appeared again

**Comment by dmahhhh** [comment]
Thanks, worked like a charm for me!

**Comment by engkazim2000** [comment]
HI,
Now plugin is showing but nothing is playing anyone facing that issue

**Comment by Cigaras** [comment]
Looks like this is solved, and @engkazim2000 comment lacks any useful details to identify his problem, so I am closing this issue.
