### ISSUE TITLE
Plugin Doesn't Show

### ISSUE THREAD

**Issue by tsposato** [Cigaras/IPTV.bundle#235]
I have Plex Version 1.18.1.1973 running on FreeBSD/FreeBSD, after installing the bundle it shows up in settings, plugins where I configured my m3u and guide. 

It saves fine but I cannot use the plugin afterwards, there is nowhere for me to click via any app or the web interface? Am I missing something here? Do I need to enable the plugin somewhere? Where would it normally appear in the web interface?

**Comment by Cigaras** [comment]
I also can no longer find any plugins in any apps, [Plex killed them...](https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/)

Some say that version 1.16 still works (#231), didn't try myself.

**Comment by tsposato** [comment]
I have manually installed the plugin however it is only visible in plugin
settings  and nowhere else...

**Comment by Cigaras** [comment]
That is correct, Plex server still sees and acknowledges plug-ins, however none of current Plex apps support them, so you need a very old Plex client app to see the plug-ins.

**Comment by tsposato** [comment]
Oh right, so it no longer works via the Plex webapp either then?

Regards,
Terry Sposato

**Comment by Cigaras** [comment]
Yes, Plex web app no longer shows any plug-ins.

Try [Kodi](https://kodi.tv/) or [Emby](https://emby.media/) or somehing [else](https://valdasv.blogspot.com/2016/03/iptv-m3u-players.html) instead.

**Comment by tsposato** [comment]
Will do, thanks.

Regards,
Terry Sposato

**Comment by TristBella** [comment]
You can use Kitana (pannal/Kitana) to view and manage plugins since Plex removed that functionality. All plugins can be viewed as if it was still in Plex.
