### ISSUE TITLE
Now Tv Plex

### ISSUE THREAD

**Issue by jamiek2k8** [Cigaras/IPTV.bundle#25]
the iptv is working on most devices but now tv,  It only started not working on the 26th which has been perfect since then,  i have done everything i could possible think off such as deleting server and starting again but nothing

**Comment by brickibezz** [comment]
nowtv will only play m3u8 files, mp4 files
check that your settings in plex hasnt changed to direct stream/transcode if they have iptv wont work.
to check go to plex, preferences, direct play. this should be set to automatic

**Comment by jamiek2k8** [comment]
I have been using the box to play my iptv for upto 6 months and then just stopped working one day, nothing changed but it just stopped working i have done everything i can possible think of but still nothing

**Comment by jamiek2k8** [comment]
also i can click on a channel and it will work, i will exit the channel and re try and it wont work,  only the odd channel will work the once its making no sence

**Comment by brickibezz** [comment]
were are you getting your streams from? i suspect that is the issue

**Comment by jamiek2k8** [comment]
Mobsters they are called,  i have also tryied a diffrent provider and it was the same, do u know anywhere els i could try? i am very greatful for the reply thank you

**Comment by brickibezz** [comment]
i now know your issue sir do you have skype i can add you?

**Comment by jamiek2k8** [comment]
hi yes please andrew.cross91  thank you i am online now

**Comment by brickibezz** [comment]
i have pm you

**Comment by brickibezz** [comment]
on skype

**Comment by jamiek2k8** [comment]
thanks accepted you

**Comment by crotinger** [comment]
I am having a similar issue not using Mobsters however. Video plays for about 10 seconds then fails.

**Comment by brickibezz** [comment]
what is your skype name and who is your provider?

**Comment by crotinger** [comment]
I'll get with you in a few when I get home

On Sun, Feb 7, 2016, 2:08 PM brickibezz <notifications@github.com> wrote:

> what is your skype name and who is your provider?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Cigaras/IPTV.bundle/issues/25#issuecomment-181098527>.
>
-- 
Regards,

Jason Crotinger
Operations Manager
Mutual TeleCommunications
jcrotinger@mtc4me.com
Office: 620.897.6200
Cell: 620.897.7236
Fax: 620.897.6211

-- 
This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
Please note that any views or opinions presented in this email are solely 
those of the author and do not necessarily represent those of the company. 
Finally, the recipient should check this email and any attachments for the 
presence of viruses. The company accepts no liability for any damage caused 
by any virus transmitted by this email. 

MTC | 365 Main, Little River, KS | www.mtc4me.com

**Comment by crotinger** [comment]
skype is jason.crotinger   the provider I'm using is husham
<http://iptv.husham.com/>

On Sun, Feb 7, 2016 at 6:31 PM Jason Crotinger <jcrotinger@mtc4me.com>
wrote:

> I'll get with you in a few when I get home
>
> On Sun, Feb 7, 2016, 2:08 PM brickibezz <notifications@github.com> wrote:
>
>> what is your skype name and who is your provider?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Cigaras/IPTV.bundle/issues/25#issuecomment-181098527>
>> .
>>
> --
> Regards,
>
> Jason Crotinger
> Operations Manager
> Mutual TeleCommunications
> jcrotinger@mtc4me.com
> Office: 620.897.6200
> Cell: 620.897.7236
> Fax: 620.897.6211
>
> --
Regards,

Jason Crotinger
Operations Manager
Mutual TeleCommunications
jcrotinger@mtc4me.com
Office: 620.897.6200
Cell: 620.897.7236
Fax: 620.897.6211

-- 
This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
Please note that any views or opinions presented in this email are solely 
those of the author and do not necessarily represent those of the company. 
Finally, the recipient should check this email and any attachments for the 
presence of viruses. The company accepts no liability for any damage caused 
by any virus transmitted by this email. 

MTC | 365 Main, Little River, KS | www.mtc4me.com

**Comment by shaun63** [comment]
hi brickbezz i have the same problem but mine shows all the channels loaded but will not play any im using smash iptv sub can u advse please thank u

**Comment by brickibezz** [comment]
add me on skype = plexflix

**Comment by oytote2** [comment]
Hi guys... I have the same problem. Did you find a solution ? ... Everytime when I reproduce my list in IPTV in Samsung Smart TV or Plex Android app, the video stops after 10 sec.

**Comment by brickibezz** [comment]
sure did, skype me
