### ISSUE TITLE
[Plex Media Server (MAC) and IPTV] - Error loading player: No playable sources found

### ISSUE THREAD

**Issue by mardolas** [Cigaras/IPTV.bundle#27]
Thank you for your excellent work.

I've the following issue: the playlist i tried properly works with VLC but it doesn't work with plex media server and IPTV. Plex shows the following message: Error loading player: No playable sources found.

Does anyone help me?

Plex media server: Version 0.9.12.19.1537-f38ac80 (latest)

**Comment by Cigaras** [comment]
Try different Plex apps, like Media Center or Home Theater, I doubt You use servers web interface as Your daily driver and it's a known fact that Plex Web is unable to play most streams, more information can be found in readme files [compatible devices and limitations](https://github.com/Cigaras/IPTV.bundle#compatible-devices-and-limitations) section, also check the [troubleshooting](https://github.com/Cigaras/IPTV.bundle#troubleshooting) section.
