### ISSUE TITLE
NOT ISSUE - Tested Samsung  plex player

### ISSUE THREAD

**Issue by MACE-Zer0** [Cigaras/IPTV.bundle#29]
Hi there , just reporting that i have a samsung smart tv , and tested the player of plex made for samsung smart tv , and you iptv plugin works without any problems , if you need more testing , or specific testing on it , just tell me and ill help out without any problems 

:)

**Comment by Cigaras** [comment]
Great news, thank You.

**Comment by Cigaras** [comment]
Great news, thank You.

However another user with J6200 series Samsung TV and Tizen OS on it is unable to play live streams on his TV, could You @MACE-Zer0 give some more details on Your setup? What server OS and Plex version are You using, whats the TV model?

**Comment by davidtorfer** [comment]
I've a j6300 tv and i can't see any list. i think my tv runs tizen (i bought it 2days ago), an updated plex server under ubuntu 15.10 and the client on sansungTv. I've downloaded the sdk but dont recognized the     real tv with de IDE.

**Comment by mcr-ksh** [comment]
just for the sake of completeness. I got a Tizen OS Samsung and its not working.

**Comment by sabildi** [comment]
any help with samsung tv for the iptv bundle ?
