### ISSUE TITLE
IPTV channel not showing up. 

### ISSUE THREAD

**Issue by sulaiman1989** [Cigaras/IPTV.bundle#30]
hello

i have followed the installation process and ended up with nothing. 
i am using linux mint 17.2. 

i have plexmediaserver folder installed in two directories 

first one: 
var/lib/plexmediaserver/library/application support/ plex media server/ plug-ins
2nd one:
usr/lib/plexmediaserver/resources/plug-ins-e0b7243

i have tried both directories without any luck. 

i am aware of this
https://support.plex.tv/hc/en-us/articles/201187666-Why-isn-t-the-channel-bundle-I-installed-showing-up-in-Plex-
but have no idea if i need to change folders around, in fact i did that and ended up with the whole plex server not working.

how do i get this channel to show up ?

**Comment by Cigaras** [comment]
So does any other channel plugins show up for You?

**Comment by sulaiman1989** [comment]
nop, only the ones that are preinstalled with plex show up

**Comment by Cigaras** [comment]
Then You should try asking on [Plex Forum](https://forums.plex.tv/categories/plex-channels) or contacting their support because I do not have a Linux machine nor I have experience setting a Plex server on one.
