### ISSUE TITLE
RTSP not working

### ISSUE THREAD

**Issue by jigzat** [Cigaras/IPTV.bundle#31]
Hello, than you for this bundle. I'm trying to use it to stream my local security cameras trough PLEX unfortunately RTSP streaming appears to be broken even with the default test streams. The RTSP stream works with  fine VLC (both M3U and STRM). When I try to play it with the browser the inspector says:

[Error] Failed to load resource: URL incompatible (rtsp://admin:PASSWORD@192.168.10.121:551//Streaming/Channels/2, line 0)
[Warning] Media element error code: 4 (plex.js, line 809)

the Plex Log says:

Jan 20, 2016 15:14:02 [0x700000d5f000] DEBUG - Plug-in com.plexapp.plugins.iptv has been used 94 times.
Jan 20, 2016 15:14:02 [0x700000d5f000] DEBUG - [com.plexapp.plugins.iptv] Sending command over HTTP (GET): /video/iptv/groups/All
Jan 20, 2016 15:14:02 [0x700000d5f000] DEBUG - HTTP requesting GET http://127.0.0.1:61634/video/iptv/groups/All
Jan 20, 2016 15:14:02 [0x700000d5f000] DEBUG - [com.plexapp.plugins.iptv] HTTP reply status 304, with 0 bytes of content.
Jan 20, 2016 15:14:02 [0x7000004ac000] DEBUG - Completed: [127.0.0.1:62327] GET /video/iptv/groups/All (8 live) GZIP 51ms 174 bytes 304 (pipelined: 19)
Jan 20, 2016 15:14:04 [0x70000021d000] DEBUG - Request: [127.0.0.1:62327] GET /video/iptv (8 live) GZIP
Jan 20, 2016 15:14:04 [0x70000021d000] DEBUG - Plug-in com.plexapp.plugins.iptv has been used 95 times.
Jan 20, 2016 15:14:04 [0x70000021d000] DEBUG - [com.plexapp.plugins.iptv] Sending command over HTTP (GET): /video/iptv
Jan 20, 2016 15:14:04 [0x70000021d000] DEBUG - HTTP requesting GET http://127.0.0.1:61634/video/iptv
Jan 20, 2016 15:14:04 [0x700000cdc000] DEBUG - Request: [127.0.0.1:62348] GET /:/plugins/com.plexapp.system/messaging/function/X1N0b3JlU2VydmljZTpJc0NoYW5uZWxCcm9rZW4_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMQpzMjQKY29tLnBsZXhhcHAucGx1Z2lucy5pcHR2czEwCmlkZW50aWZpZXJyMAo_ (8 live) GZIP
Jan 20, 2016 15:14:04 [0x700000cdc000] DEBUG - [com.plexapp.system] Sending command over HTTP (GET): /:/plugins/com.plexapp.system/messaging/function/X1N0b3JlU2VydmljZTpJc0NoYW5uZWxCcm9rZW4_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMQpzMjQKY29tLnBsZXhhcHAucGx1Z2lucy5pcHR2czEwCmlkZW50aWZpZXJyMAo_
Jan 20, 2016 15:14:04 [0x700000cdc000] DEBUG - HTTP requesting GET http://127.0.0.1:61376/:/plugins/com.plexapp.system/messaging/function/X1N0b3JlU2VydmljZTpJc0NoYW5uZWxCcm9rZW4_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMQpzMjQKY29tLnBsZXhhcHAucGx1Z2lucy5pcHR2czEwCmlkZW50aWZpZXJyMAo_
Jan 20, 2016 15:14:04 [0x700000cdc000] DEBUG - [com.plexapp.system] HTTP reply status 200, with 32 bytes of content.
Jan 20, 2016 15:14:04 [0x7000004ac000] DEBUG - Completed: [127.0.0.1:62348] GET /:/plugins/com.plexapp.system/messaging/function/X1N0b3JlU2VydmljZTpJc0NoYW5uZWxCcm9rZW4_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMQpzMjQKY29tLnBsZXhhcHAucGx1Z2lucy5pcHR2czEwCmlkZW50aWZpZXJyMAo_ (8 live) GZIP 4ms 331 bytes 200
Jan 20, 2016 15:14:04 [0x70000021d000] DEBUG - [com.plexapp.plugins.iptv] HTTP reply status 304, with 0 bytes of content.
Jan 20, 2016 15:14:04 [0x7000004ac000] DEBUG - Completed: [127.0.0.1:62327] GET /video/iptv (8 live) GZIP 16ms 174 bytes 304 (pipelined: 20)
Jan 20, 2016 15:14:04 [0x700000c59000] DEBUG - Request: [127.0.0.1:62327] GET /video/iptv/createvideoclipobject?container=True&thumb=&title=Entrada&url=rtsp%3A%2F%2Fadmin%3APASSWORD%40192.168.10.121%3A551%2F%2FStreaming%2FChannels%2F2 (8 live) GZIP
Jan 20, 2016 15:14:04 [0x700000c59000] DEBUG - Plug-in com.plexapp.plugins.iptv has been used 96 times.
Jan 20, 2016 15:14:04 [0x700000c59000] DEBUG - [com.plexapp.plugins.iptv] Sending command over HTTP (GET): /video/iptv/createvideoclipobject?container=True&thumb=&title=Entrada&url=rtsp%3A%2F%2Fadmin%3APASSWORD%40192.168.10.121%3A551%2F%2FStreaming%2FChannels%2F2
Jan 20, 2016 15:14:04 [0x700000c59000] DEBUG - HTTP requesting GET http://127.0.0.1:61634/video/iptv/createvideoclipobject?container=True&thumb=&title=Entrada&url=rtsp%3A%2F%2Fadmin%3APASSWORD%40192.168.10.121%3A551%2F%2FStreaming%2FChannels%2F2
Jan 20, 2016 15:14:04 [0x700000c59000] DEBUG - [com.plexapp.plugins.iptv] HTTP reply status 304, with 0 bytes of content.
Jan 20, 2016 15:14:04 [0x70000052f000] DEBUG - Completed: [127.0.0.1:62327] GET /video/iptv/createvideoclipobject?container=True&thumb=&title=Entrada&url=rtsp%3A%2F%2Fadmin%3APASSWORD%40192.168.10.121%3A551%2F%2FStreaming%2FChannels%2F2 (8 live) GZIP 8ms 174 bytes 304 (pipelined: 21)
Jan 20, 2016 15:14:04 [0x700000d5f000] DEBUG - Request: [127.0.0.1:62327] GET /photo/:/transcode?url=http%3A%2F%2F127.0.0.1%3A32400%2F%3A%2Fplugins%2Fcom.plexapp.plugins.iptv%2Fresources%2Ficon-default.png%3Ft%3D1449811026&width=250&height=141&minSize=1 (8 live) GZIP
Jan 20, 2016 15:14:04 [0x700000d5f000] DEBUG - Photo transcoder: Request for url [http://127.0.0.1:32400/:/plugins/com.plexapp.plugins.iptv/resources/icon-default.png?t=1449811026](is local: 1 upscaled: 0)
Jan 20, 2016 15:14:04 [0x700000bd6000] DEBUG - Request: [127.0.0.1:62328] GET /photo/:/transcode?url=http%3A%2F%2F127.0.0.1%3A32400%2Fsystem%2Fbundle%2Fmedia%2Fflags%2FaudioCodec%2Faac%3Ft%3Dundefined&width=100&height=20 (7 live) GZIP
Jan 20, 2016 15:14:04 [0x700000d5f000] DEBUG - Content-Length of /Users/samir/Library/Caches/PlexMediaServer/PhotoTranscoder/cd/cd90fbb505ba94d89161a2e238c7fc276114b0f7.jpg is 60874.
Jan 20, 2016 15:14:04 [0x700000bd6000] DEBUG - Photo transcoder: Request for url [http://127.0.0.1:32400/system/bundle/media/flags/audioCodec/aac?t=undefined](is local: 1 upscaled: 0)
Jan 20, 2016 15:14:04 [0x70000052f000] DEBUG - Completed: [127.0.0.1:62327] GET /photo/:/transcode?url=http%3A%2F%2F127.0.0.1%3A32400%2F%3A%2Fplugins%2Fcom.plexapp.plugins.iptv%2Fresources%2Ficon-default.png%3Ft%3D1449811026&width=250&height=141&minSize=1 (7 live) GZIP 1ms 60874 bytes 200 (pipelined: 22)
Jan 20, 2016 15:14:04 [0x700000bd6000] DEBUG - Content-Length of /Users/samir/Library/Caches/PlexMediaServer/PhotoTranscoder/e5/e58de77c0bdc7de6d8bf4770aaeb93a0d6f8a993.jpg is 1840.
Jan 20, 2016 15:14:04 [0x70000052f000] DEBUG - Completed: [127.0.0.1:62328] GET /photo/:/transcode?url=http%3A%2F%2F127.0.0.1%3A32400%2Fsystem%2Fbundle%2Fmedia%2Fflags%2FaudioCodec%2Faac%3Ft%3Dundefined&width=100&height=20 (7 live) GZIP 0ms 1840 bytes 200 (pipelined: 35)
Jan 20, 2016 15:14:06 [0x700000cdc000] DEBUG - Request: [127.0.0.1:62327] GET /photo/:/transcode?url=http%3A%2F%2F127.0.0.1%3A32400%2F%3A%2Fplugins%2Fcom.plexapp.plugins.iptv%2Fresources%2Ficon-default.png%3Ft%3D1449811026&width=100&height=150&minSize=1 (7 live) GZIP
Jan 20, 2016 15:14:06 [0x700000cdc000] DEBUG - Photo transcoder: Request for url [http://127.0.0.1:32400/:/plugins/com.plexapp.plugins.iptv/resources/icon-default.png?t=1449811026](is local: 1 upscaled: 0)
Jan 20, 2016 15:14:06 [0x700000cdc000] DEBUG - Content-Length of /Users/samir/Library/Caches/PlexMediaServer/PhotoTranscoder/10/107747bbd0e4ee12a656044129b942a2f39d95a8.jpg is 27479.
Jan 20, 2016 15:14:06 [0x70000052f000] DEBUG - Completed: [127.0.0.1:62327] GET /photo/:/transcode?url=http%3A%2F%2F127.0.0.1%3A32400%2F%3A%2Fplugins%2Fcom.plexapp.plugins.iptv%2Fresources%2Ficon-default.png%3Ft%3D1449811026&width=100&height=150&minSize=1 (7 live) GZIP 1ms 27479 bytes 200 (pipelined: 23)
Jan 20, 2016 15:14:06 [0x70000021d000] DEBUG - Request: [127.0.0.1:62327] GET /video/iptv/createvideoclipobject?container=True&thumb=**NONE**&title=Entrada&url=rtsp%3A%2F%2Fadmin%3APASSWORD%40192.168.10.121%3A551%2F%2FStreaming%2FChannels%2F2 (7 live) GZIP
Jan 20, 2016 15:14:06 [0x70000021d000] DEBUG - Plug-in com.plexapp.plugins.iptv has been used 97 times.
Jan 20, 2016 15:14:06 [0x70000021d000] DEBUG - [com.plexapp.plugins.iptv] Sending command over HTTP (GET): /video/iptv/createvideoclipobject?container=True&thumb=**NONE**&title=Entrada&url=rtsp%3A%2F%2Fadmin%3APASSWORD%40192.168.10.121%3A551%2F%2FStreaming%2FChannels%2F2
Jan 20, 2016 15:14:06 [0x70000021d000] DEBUG - HTTP requesting GET http://127.0.0.1:61634/video/iptv/createvideoclipobject?container=True&thumb=__NONE__&title=Entrada&url=rtsp%3A%2F%2Fadmin%3APASSWORD%40192.168.10.121%3A551%2F%2FStreaming%2FChannels%2F2
Jan 20, 2016 15:14:06 [0x70000021d000] DEBUG - [com.plexapp.plugins.iptv] HTTP reply status 304, with 0 bytes of content.
Jan 20, 2016 15:14:06 [0x7000004ac000] DEBUG - Completed: [127.0.0.1:62327] GET /video/iptv/createvideoclipobject?container=True&thumb=**NONE**&title=Entrada&url=rtsp%3A%2F%2Fadmin%3APASSWORD%40192.168.10.121%3A551%2F%2FStreaming%2FChannels%2F2 (7 live) GZIP 8ms 174 bytes 304 (pipelined: 24)
Jan 20, 2016 15:14:58 [0x70000052f000] ERROR - handle_stream_read error 2 End of file
Jan 20, 2016 15:14:58 [0x70000052f000] DEBUG - Removing notification stream because of error.

**Comment by Cigaras** [comment]
That is Plex clients issue, not the plugins, try playing it with [Plex Media Center](https://github.com/Cigaras/IPTV.bundle#compatible-devices-and-limitations) or [Plex Home Theater](https://github.com/Cigaras/IPTV.bundle#compatible-devices-and-limitations) app.

**Comment by Cigaras** [comment]
#62
