### ISSUE TITLE
RTP support?

### ISSUE THREAD

**Issue by meliborn** [Cigaras/IPTV.bundle#32]
Do you support urls like rtp://@231.1.1.1:1234 in playlist?

**Comment by Cigaras** [comment]
Just give it a try, I have no idea what kind of link is this, but plugin will pass the handling to Plex using native `HTTPLiveStreamURL()` function, if Plex can handle it then it will play.

Alternatively You could change link to `rtmp://...` and [enable RTMP](https://github.com/Cigaras/IPTV.bundle#supported-protocols) in plugin settings, then it'll try native `RTMPVideoURL()` function, but it rarely works.

**Comment by denniseffing** [comment]
In my country (Germany) the ISP "Telekom" offers IP TV which they call Entertain. Telekom doesn't officially support watching the streams without set-top box, but there is a way to watch them over certain RTP URLs with VLC Media Player, as long as you are in your own network which uses Entertain.

So I wanted to try this with your IPTV Plugin.
For testing purposes, I tried to add a single channel, the playlist looks like this:
```
#EXTM3U
#EXTINF:0 tvg-id="ARD" tvg-name="Das Erste" group-title="TV",Das Erste (RTP)
rtp://@239.35.10.4:10000
```

This doesn't work however, when I try to access the channel via Plex Webapplication I get the following error: 
```
Error loading player:
No playable sources found
```

I guess RTP URLS do not work.

**Comment by EmilioMoreno** [comment]
@meliborn Plex does not support rtp as far as i know, as this involves dealing with IGMP and multicast; simplest solution is install udpxy to convert multicast streams to unicast.

So basically you will install udpxy, run  on some device on the network, and create the lists with urls like http://ip_of_udpxy_server:port_udpxy/rtp/239.35.10.4:10000.
