### ISSUE TITLE
User Agent

### ISSUE THREAD

**Issue by txt3rob** [Cigaras/IPTV.bundle#33]
Hi Dude,

Is there an easy way to set the user-agent to the plex player?

got streams restricted to certain devices i would like to fake the header for.

i.e ipad only ones.

**Comment by Cigaras** [comment]
Sorry, I can't help You with this.

**Comment by Cigaras** [comment]
Custom User-Agent support has been added in version [2.0.0](https://github.com/Cigaras/IPTV.bundle/releases/tag/v2.0.0), more information can be fount in issue #79
