### ISSUE TITLE
Plex IPTV Black Now TV Box - Video Unavailable

### ISSUE THREAD

**Issue by RobKelz** [Cigaras/IPTV.bundle#35]
Hi,

Wondering if you can help with some problems I am having.

I have had Plex on my server for around 2 years now all has been well and good without fail, I decided to install IPTV but cannot seem to get it working correctly and stable.

I have tried many providers of IPTV and many of them fail, or some will work and some don't. I have also made sure they are transcoding their stream to MP4 (H264/AAC) and this has been correct.

The stream works perfectly fine in VLC but just will not play on the Now TV box, it is the later version of the Now TV box (black model) and I am using Automatic play mode and not Direct Play or Direct Stream.

Any help would be muchly appreciated as this is now getting very frustrating.

Many thanks,
Rob

**Comment by smithy5271** [comment]
Hi Rob have you had any joy with iptv on plex ??
I hear it can be used on the now tv box I have but finding info is extremely difficult. 
Any advice would be great

**Comment by Cigaras** [comment]
Sorry to hear that, but I do not have a TV box, and usually it's Plex clients app fault to not be able to play some streams and there is nothing I can do. Some people had luck using intermediate transcoding software like [TVHeadend](https://forums.plex.tv/discussion/comment/544372#Comment_544372) or VODSever. Also from time tome Plex updates its clients apps and enhance (or fix) live streams playing capabilities, like they did with Plex Home Theater.
