### ISSUE TITLE
Can't open list .ch

### ISSUE THREAD

**Issue by ntassani** [Cigaras/IPTV.bundle#36]
Hi! Exist any way for open an itv list with .ch links?

This file for example:
#EXTM3U
#EXTINF:-1,1 Classics
http://74.208.164.55:80/tvultimate/tvultimate/102.ch
#EXTINF:-1,A&E
http://74.208.164.55:80/tvultimate/tvultimate/19.ch
#EXTINF:-1,AMC
http://74.208.164.55:80/tvultimate/tvultimate/79.ch
#EXTINF:-1,Animal Planet
http://74.208.164.55:80/tvultimate/tvultimate/59.ch
#EXTINF:-1,AXN
http://74.208.164.55:80/tvultimate/tvultimate/20.ch
#EXTINF:-1,Az Cinema
http://74.208.164.55:80/tvultimate/tvultimate/73.ch
#EXTINF:-1,Az Clic
http://74.208.164.55:80/tvultimate/tvultimate/7.ch
#EXTINF:-1,Az Corazon
http://74.208.164.55:80/tvultimate/tvultimate/5.ch
#EXTINF:-1,Az Mundo
http://74.208.164.55:80/tvultimate/tvultimate/39.ch
#EXTINF:-1,Az Noticias
http://74.208.164.55:80/tvultimate/tvultimate/1.ch
#EXTINF:-1,Azteca Siete
http://74.208.164.55:80/tvultimate/tvultimate/2.ch
#EXTINF:-1,Azteca Trece
http://74.208.164.55:80/tvultimate/tvultimate/3.ch
#EXTINF:-1,BANDAMAX
http://74.208.164.55:80/tvultimate/tvultimate/104.ch
#EXTINF:-1,BBC Entertainment
http://74.208.164.55:80/tvultimate/tvultimate/27.ch
#EXTINF:-1,Boomerang
http://74.208.164.55:80/tvultimate/tvultimate/51.ch
#EXTINF:-1,Canal Cinco
http://74.208.164.55:80/tvultimate/tvultimate/8.ch
#EXTINF:-1,Canal de las Estrellas
http://74.208.164.55:80/tvultimate/tvultimate/6.ch
#EXTINF:-1,Cartoon Network
http://74.208.164.55:80/tvultimate/tvultimate/49.ch
#EXTINF:-1,cbeebies
http://74.208.164.55:80/tvultimate/tvultimate/42.ch
#EXTINF:-1,Cinecanal
http://74.208.164.55:80/tvultimate/tvultimate/74.ch
#EXTINF:-1,Cinemax
http://74.208.164.55:80/tvultimate/tvultimate/81.ch
#EXTINF:-1,Comedy Central
http://74.208.164.55:80/tvultimate/tvultimate/22.ch
#EXTINF:-1,De pelicula HD
http://74.208.164.55:80/tvultimate/tvultimate/78.ch
#EXTINF:-1,Discovery
http://74.208.164.55:80/tvultimate/tvultimate/58.ch
#EXTINF:-1,Discovery Civilization
http://74.208.164.55:80/tvultimate/tvultimate/64.ch
#EXTINF:-1,Discovery Kids
http://74.208.164.55:80/tvultimate/tvultimate/41.ch
#EXTINF:-1,Discovery Science
http://74.208.164.55:80/tvultimate/tvultimate/63.ch
#EXTINF:-1,Discovery Theather
http://74.208.164.55:80/tvultimate/tvultimate/54.ch
#EXTINF:-1,Discovery Turbo
http://74.208.164.55:80/tvultimate/tvultimate/65.ch
#EXTINF:-1,Discovery World
http://74.208.164.55:80/tvultimate/tvultimate/57.ch
#EXTINF:-1,Disney channel
http://74.208.164.55:80/tvultimate/tvultimate/45.ch
#EXTINF:-1,disney junior
http://74.208.164.55:80/tvultimate/tvultimate/43.ch
#EXTINF:-1,Disney XD
http://74.208.164.55:80/tvultimate/tvultimate/50.ch
#EXTINF:-1,Distrito Comedia
http://74.208.164.55:80/tvultimate/tvultimate/37.ch
#EXTINF:-1,E!
http://74.208.164.55:80/tvultimate/tvultimate/28.ch
#EXTINF:-1,El financiero Bloomberg
http://74.208.164.55:80/tvultimate/tvultimate/96.ch
#EXTINF:-1,ESPN
http://74.208.164.55:80/tvultimate/tvultimate/88.ch
#EXTINF:-1,ESPN 2
http://74.208.164.55:80/tvultimate/tvultimate/93.ch
#EXTINF:-1,ESPN 3
http://74.208.164.55:80/tvultimate/tvultimate/89.ch
#EXTINF:-1,Estrella Tv
http://74.208.164.55:80/tvultimate/tvultimate/12.ch
#EXTINF:-1,Fashion Tv
http://74.208.164.55:80/tvultimate/tvultimate/25.ch
#EXTINF:-1,Film Zone HD
http://74.208.164.55:80/tvultimate/tvultimate/77.ch
#EXTINF:-1,Formula1
http://74.208.164.55:80/tvultimate/tvultimate/87.ch
#EXTINF:-1,Foro TV
http://74.208.164.55:80/tvultimate/tvultimate/9.ch
#EXTINF:-1,Fox
http://74.208.164.55:80/tvultimate/tvultimate/14.ch
#EXTINF:-1,Fox 1 HD
http://74.208.164.55:80/tvultimate/tvultimate/68.ch
#EXTINF:-1,Fox Action HD
http://74.208.164.55:80/tvultimate/tvultimate/69.ch
#EXTINF:-1,Fox Cinema
http://74.208.164.55:80/tvultimate/tvultimate/71.ch
#EXTINF:-1,Fox Classics
http://74.208.164.55:80/tvultimate/tvultimate/72.ch
#EXTINF:-1,Fox Life
http://74.208.164.55:80/tvultimate/tvultimate/36.ch
#EXTINF:-1,Fox Movies HD
http://74.208.164.55:80/tvultimate/tvultimate/70.ch
#EXTINF:-1,Fox Sports
http://74.208.164.55:80/tvultimate/tvultimate/90.ch
#EXTINF:-1,Fox Sports 2
http://74.208.164.55:80/tvultimate/tvultimate/91.ch
#EXTINF:-1,FX
http://74.208.164.55:80/tvultimate/tvultimate/18.ch
#EXTINF:-1,Garage Tv
http://74.208.164.55:80/tvultimate/tvultimate/34.ch
#EXTINF:-1,Glitz
http://74.208.164.55:80/tvultimate/tvultimate/35.ch
#EXTINF:-1,Golden Edge
http://74.208.164.55:80/tvultimate/tvultimate/83.ch
#EXTINF:-1,Golden HD
http://74.208.164.55:80/tvultimate/tvultimate/76.ch
#EXTINF:-1,Gourmet
http://74.208.164.55:80/tvultimate/tvultimate/33.ch
#EXTINF:-1,H mx
http://74.208.164.55:80/tvultimate/tvultimate/13.ch
#EXTINF:-1,H&H
http://74.208.164.55:80/tvultimate/tvultimate/60.ch
#EXTINF:-1,History
http://74.208.164.55:80/tvultimate/tvultimate/55.ch
#EXTINF:-1,Hola Tv
http://74.208.164.55:80/tvultimate/tvultimate/24.ch
#EXTINF:-1,Investigation Discovery ID
http://74.208.164.55:80/tvultimate/tvultimate/31.ch
#EXTINF:-1,Isat
http://74.208.164.55:80/tvultimate/tvultimate/85.ch
#EXTINF:-1,Lifetime
http://74.208.164.55:80/tvultimate/tvultimate/62.ch
#EXTINF:-1,Mas Chic
http://74.208.164.55:80/tvultimate/tvultimate/26.ch
#EXTINF:-1,Milenio
http://74.208.164.55:80/tvultimate/tvultimate/95.ch
#EXTINF:-1,MTV
http://74.208.164.55:80/tvultimate/tvultimate/100.ch
#EXTINF:-1,MTV HITS
http://74.208.164.55:80/tvultimate/tvultimate/101.ch
#EXTINF:-1,Mtv Live HD
http://74.208.164.55:80/tvultimate/tvultimate/98.ch
#EXTINF:-1,Natgeo wild
http://74.208.164.55:80/tvultimate/tvultimate/56.ch
#EXTINF:-1,National Geographic
http://74.208.164.55:80/tvultimate/tvultimate/61.ch
#EXTINF:-1,Nick
http://74.208.164.55:80/tvultimate/tvultimate/48.ch
#EXTINF:-1,Nick HD
http://74.208.164.55:80/tvultimate/tvultimate/47.ch
#EXTINF:-1,NIck Jr
http://74.208.164.55:80/tvultimate/tvultimate/44.ch
#EXTINF:-1,NickToons
http://74.208.164.55:80/tvultimate/tvultimate/46.ch
#EXTINF:-1,PENDIENTE 480
http://74.208.164.55:80/tvultimate/tvultimate/94.ch
#EXTINF:-1,Proyecto 40
http://74.208.164.55:80/tvultimate/tvultimate/4.ch
#EXTINF:-1,PX TV
http://74.208.164.55:80/tvultimate/tvultimate/92.ch
#EXTINF:-1,RITMOSON
http://74.208.164.55:80/tvultimate/tvultimate/103.ch
#EXTINF:-1,Sony
http://74.208.164.55:80/tvultimate/tvultimate/15.ch
#EXTINF:-1,SPACE
http://74.208.164.55:80/tvultimate/tvultimate/80.ch
#EXTINF:-1,Studio Universal
http://74.208.164.55:80/tvultimate/tvultimate/84.ch
#EXTINF:-1,Syfy
http://74.208.164.55:80/tvultimate/tvultimate/30.ch
#EXTINF:-1,TBS Veryfunny
http://74.208.164.55:80/tvultimate/tvultimate/38.ch
#EXTINF:-1,TCM
http://74.208.164.55:80/tvultimate/tvultimate/86.ch
#EXTINF:-1,Teleformula
http://74.208.164.55:80/tvultimate/tvultimate/11.ch
#EXTINF:-1,TELEHIT HD
http://74.208.164.55:80/tvultimate/tvultimate/99.ch
#EXTINF:-1,TIIN
http://74.208.164.55:80/tvultimate/tvultimate/52.ch
#EXTINF:-1,TLC
http://74.208.164.55:80/tvultimate/tvultimate/66.ch
#EXTINF:-1,TNT
http://74.208.164.55:80/tvultimate/tvultimate/82.ch
#EXTINF:-1,TNT HD
http://74.208.164.55:80/tvultimate/tvultimate/75.ch
#EXTINF:-1,TNT Series
http://74.208.164.55:80/tvultimate/tvultimate/32.ch
#EXTINF:-1,TOONCAST
http://74.208.164.55:80/tvultimate/tvultimate/53.ch
#EXTINF:-1,Trendy Channel
http://74.208.164.55:80/tvultimate/tvultimate/40.ch
#EXTINF:-1,Tru Tv HD
http://74.208.164.55:80/tvultimate/tvultimate/21.ch
#EXTINF:-1,Tve
http://74.208.164.55:80/tvultimate/tvultimate/97.ch
#EXTINF:-1,Unicable
http://74.208.164.55:80/tvultimate/tvultimate/23.ch
#EXTINF:-1,Universal Channel
http://74.208.164.55:80/tvultimate/tvultimate/29.ch
#EXTINF:-1,Universal Channel HD
http://74.208.164.55:80/tvultimate/tvultimate/17.ch
#EXTINF:-1,UTV 360
http://74.208.164.55:80/tvultimate/tvultimate/10.ch
#EXTINF:-1,Warner Brothers
http://74.208.164.55:80/tvultimate/tvultimate/16.ch
#EXTINF:-1,WOBI
http://74.208.164.55:80/tvultimate/tvultimate/67.ch
#EXTINF:-1,ESPN 3 TEST
http://74.208.164.55:80/tvultimate/tvultimate/105.ch

Thanks for your help! :)

**Comment by Cigaras** [comment]
I can't play mentioned streams in VLC either, and most likely Plex client You are trying to play it is not able to do so, so as usual my suggestions would be to try VLC, try Plex Media Center, try the \*.strm file method to detect the source of the issue, all described in readme file [troubleshooting section](https://github.com/Cigaras/IPTV.bundle#troubleshooting).

But as I said, most likely Plex wont be able to play them, You might want to take a look at alternative media player like [Kodi](http://kodi.wiki/view/Add-on:IPTV_Simple_Client) or [MediaPortal](http://wiki.team-mediaportal.com/1_MEDIAPORTAL_1/141_Configuration/TV-Server_Configuration/02_TV_Servers/0_IPTV_(DVB-IP)) or You can try using third party transcoding software like [VODServer](http://vodserver.sourceforge.net/) or similar, however it is quite complicated.
