### ISSUE TITLE
Channel can't play a MP4 video stream.

### ISSUE THREAD

**Issue by b2232252** [Cigaras/IPTV.bundle#37]
Hello! I'm using IPTV.bundle on my Samsung Smart TV Plex client and I run into error while loading a MP4 stream on the web. Accessing to the same channel via browser the video is played without any issue.
Follow all necessary info. Can you help me to solve this problem, please?

App & TV info:
Samsung UE46ES800 E-Series (2012 model)
Plex 2.005 PMS Version 0.9.15.6.1714-7be11e1

Video stream: [Italian Movie Trailer](http://www.megahd.tv/embed-2n3jss8zw7th.html)

Here you while find smart hub client debug file (Plex Media Server.log) for detailed error info: [http://pastebin.com/raw/GTjrNtCg](http://pastebin.com/raw/GTjrNtCg)

Finally, my Smart TV support this MP4 stream because tv browser can play this stream.

Many thanks!
Albert

**Comment by Cigaras** [comment]
This is not a live stream, this is just a regular MP4 file lying on the internet, like a Youtube video, and your supplied link does not link directly to mentioned video, it links to a flash player ([jwplayer](https://www.jwplayer.com/) if I am not mistaken) that plays the video, and Plex isn't a fan of external webkit players.

Long story short, it's not an IPTV stream, You need a dedicated channel plugin for it (that would use a dedicated MegaHD [URL Service](https://support.plex.tv/hc/en-us/articles/201382123-The-Power-of-the-URL-Service) and as I know it [does not exists](https://github.com/plexinc-plugins/Services.bundle/tree/master/Contents/Service%20Sets), it might be that MegaHD are the only ones who can make such a service and/or Plex channel).
