### ISSUE TITLE
IPTV .ts streams

### ISSUE THREAD

**Issue by kale79** [Cigaras/IPTV.bundle#40]
I have a problem playing my IPTV list with channels ending with .ts.
I have tried on PMS and PHT as well as on Samsung Plex App.
Getting 

Error Loading Player
No playable source found.

List is working fine on SmartIPTV app for SamsungTV and in VLC player.

Any help would be appreciated.

**Comment by txt3rob** [comment]
use HLS as it will work

**Comment by kale79** [comment]
Could you explain me how to do it ? I have http address of the server with user/pass and .ts at the end of line for each channel. Is there a way to convert to HLS or what ??? Sorry if question is stupid but I am new to this completely :)

**Comment by Be4stElectrjc** [comment]
Try all combinations:

Direct Play Disable Direct Stream Disable Only this works with my streams
Direct Play Enable Direct Stream Disable
Direct Play Disable Direct Stream Enable
Direct Play Enable Direct Stream Enable

My streams:

Media
Container MPEGTS
Protocol hls
Web Optimized Yes
Part
Container MPEGTS
Web Optimized Yes
Codec H264
Codec AAC

**Comment by stefanoromanello** [comment]
Same problem here.. Can't play .ts file

**Comment by FezVrasta** [comment]
Same problem, can't really find a way to get them to work... I have access only to .ts streams

**Comment by Luisfmarkes** [comment]
+1
Having the same problem! :\

**Comment by plexmediaserver** [comment]
Open your paylist.m3u with notepad ++ at the end of every stream link it will say .ts change them all to .m3u8 save then restart plex and your done

**Comment by plexmediaserver** [comment]
Open your playlist.m3u with notepad ++ at the end of every stream link it will say .ts change them all to .m3u8 save then restart plex and your done
