### ISSUE TITLE
[TIP] Plex Media Player

### ISSUE THREAD

**Issue by Codehhh** [Cigaras/IPTV.bundle#41]
Plex Media player plays HTTP streams perfectly! Feel free to update the README.

**Comment by Cigaras** [comment]
I'm a bit confused here, what software carries the name of "Plex Media Player"? Looks like it is a peace of software included in Plex Home Theater package responsible for playback, isn't it?

**Comment by Cigaras** [comment]
Oh, I got it, it's the Plex Home Theater replacement currently available only to Plex Pass users (https://blog.plex.tv/2015/10/20/introducing-the-plex-media-player/)
