### ISSUE TITLE
Error "Server Not Available"

### ISSUE THREAD

**Issue by Be4stElectrjc** [Cigaras/IPTV.bundle#42]
Using IPTV.bundle plugin on Plex Media Server from Xbox One Plex App i go to my IPTV channels, i choose one to see and the second before to play it i get server not available. But i'm connected to my server, that is up and running. I would say that Plex Media Server can play the m3u file, it's not a problem of the file.

This is the discussion on Plex Players on their forum and there's my log.

https://forums.plex.tv/discussion/218802/error-server-not-available#latest

**Comment by Cigaras** [comment]
As You already figured out, its Plex issue not plugins and I am afraid I wont be able to help You. Custom trascoder might do the trick, but again as I do not have an Xbox and do not know what streams does it support or expects, I do not know what trascoding settings to suggest You.

Also I would be more interested in plugins log, not the servers log, file named *com.plexapp.plugins.iptv.log*, located in folder *PMS Plugin Logs*, check [documentation](https://support.plex.tv/hc/en-us/articles/200250417-Plex-Media-Server-Log-Files) for exact location depending on Your system.

**Comment by Be4stElectrjc** [comment]
I will upload here, just wait 10 minutes. I have this idea:

https://forums.plex.tv/discussion/218884/plex-dlna-server-xbox-one-problem#latest
