### ISSUE TITLE
Remove the preferences in plex

### ISSUE THREAD

**Issue by maverick1105** [Cigaras/IPTV.bundle#43]
Is there anyway to remove the preferences options at the end of the channel list on some devices?

**Comment by Cigaras** [comment]
Try commenting out line [104](https://github.com/Cigaras/IPTV.bundle/blob/master/Contents/Code/__init__.py#L104) in `__init__.py` file byt adding `#` at the start:

    #oc.add(PrefsObject(title = unicode(L('Preferences')), thumb = R('icon-prefs.png')))

It might cause preferences to disappear from server management, but it shouldn't, I am not sure :)
