### ISSUE TITLE
iOS no content with AceProxy

### ISSUE THREAD

**Issue by sei4eto** [Cigaras/IPTV.bundle#45]
Hello!
I can't get m3u playlist from AceProxy installed on Windows 10 machine. I've tried both torrenttv and p2pproxy plugin. The client (iOS) shows no content message. The playlist link works on a browser or other players.
Ideas?
Thanks!

**Comment by Cigaras** [comment]
I can not help You with AceProxy, but maybe I can tell something if You show me Your playlist and plug-in log file [com.plexapp.plugins.iptv.log](https://github.com/Cigaras/IPTV.bundle/wiki/Troubleshooting).
