### ISSUE TITLE
and after a while the TV falls and connect plex Service stopped working

### ISSUE THREAD

**Issue by Webmasterparis** [Cigaras/IPTV.bundle#51]
Hello

I have an Ubuntu 15.05 Server and Plex media server Version: plexmediaserver_0.9.8.5.165-c301c50_amd64 with plexconnect v 0.5 for connecting to Apple TV, your plugin works for 25 to 30 minutes and then after the plex medi sever service crash ??

you have a solution to problem?

**Comment by Cigaras** [comment]
No, I do not.
