### ISSUE TITLE
Streams won't play - synology based server

### ISSUE THREAD

**Issue by spitfire852** [Cigaras/IPTV.bundle#52]
Hi i am having issues getting the streams to play. It seems that anything that is ondemand off my IPTV supplier is okay and works however, anything that is a live stream doesn't and just says there was a problem. I have tried on the browser and other clients no luck. 

Stream works fine on other m3u streaming apps and also on vlc on the computer.  Any ideas?

**Comment by Nightmarel33t** [comment]
I have the same issue with .ts extensions using http URL's end of the playlist

**Comment by Cigaras** [comment]
Some say (#40) renaming .ts to .m3u8 does the trick, also try fiddling with [Direct Play and Direct Stream](https://github.com/Cigaras/IPTV.bundle#troubleshooting) options in Your clients settings.
