### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by freddysmith1** [Cigaras/IPTV.bundle#54]
Hi not sure if its possible but is there anyway to get the category icons from a png file in resource folder?   like the icon-folder.png but have different png files for each category 

basically category A grabs the png file called sport.png 
               category b grabs png file called movies.png

**Comment by Cigaras** [comment]
Yes, add attribute `group-logo="sport.png"` for the first channel in the category and it should to work, more info including example in [readme file](https://github.com/Cigaras/IPTV.bundle#playlist-structure-and-examples).
