### ISSUE TITLE
Too big playlist issue

### ISSUE THREAD

**Issue by kampiamodikuesto** [Cigaras/IPTV.bundle#57]
hi, i have a iptv list that work on iptv simple app on android tv but if i use with plex no channel are found. So is there a tool to check my list to know if it's compatible with your addon?

from my list:
# EXTM3U
# EXTINF:-1,- - - I T A L I A - - -

http:// ..... /1kx.m3u8
# EXTINF:-1,Rai 1 HD

http:// ..... /xy.m3u8
.....

**Comment by Cigaras** [comment]
For playlist to be compatible with my plugin it just needs to match the [M3U](https://en.wikipedia.org/wiki/M3U) structure, however for the sources listed in the list to be playable  Plex must be able to handle them, and as there is a plethora of Plex software [variations](https://www.plex.tv/apps/) and it is always in development it is not possible to have one tool to check them all.

**Comment by kampiamodikuesto** [comment]
Find the problem, my list is too long, if i use the list partially it works with plex and your plugin. Is there a way to fix this?

**Comment by Cigaras** [comment]
Do You really need a list that big? I had no issues with list of over 200 channels, never tried a bigger but I know it chokes if supplied with a few thousands of channels, maybe someday will look deeper into this issue, but definitely not the highest priority.

**Comment by kampiamodikuesto** [comment]
i have a list of more 1000 channel:( i would like to not edit the list each update. is there a way to check compatibility?

**Comment by Cigaras** [comment]
Fixed in version [1.2.5](https://github.com/Cigaras/IPTV.bundle/releases/latest) by adding pagination and showing limited amount of channels at a time.

**Comment by kampiamodikuesto** [comment]
Great:) thanks. The next step i think will be "zappig feature" as Extrem Iptv app do in other words, choose channel by number.

**Comment by Cigaras** [comment]
Please provide a list that does not work.

What is Extreme Iptv app?

**Comment by kampiamodikuesto** [comment]
You are right, 200 channel is the best option. I'll meke a script with automator to save only 200 first channel.

is an app for android, i think is the best for iptv. We can digit a number to see each channel.
