### ISSUE TITLE
Duplicate items when using multiple categories

### ISSUE THREAD

**Issue by pertile153** [Cigaras/IPTV.bundle#60]
I would like to know if you can put an item in several categories.
I created several different items in different categories but when I open 'all' they keep repeating

Sorry bad english

**Comment by Cigaras** [comment]
At the moment no, might add in the future.

**Comment by Cigaras** [comment]
Fixed duplicate items in "All" list in version [1.2.5](https://github.com/Cigaras/IPTV.bundle/releases/latest), update and enjoy.

**Comment by Cigaras** [comment]
Somethings not working, some clients still show duplicate items

**Comment by Cigaras** [comment]
Fixed in version [1.2.6](../releases/tag/v1.2.6).
