### ISSUE TITLE
Not working with PlexConnect and ATV3 iOS 7.2.1

### ISSUE THREAD

**Issue by blackfed** [Cigaras/IPTV.bundle#61]
Hi, i have plexconnect on an ATV3 and I have your plugin, it doesn't play any channel, it says:"Trailer not disponible at the moment" 
Do you know how to fix this?
Thanks you so much

**Comment by Cigaras** [comment]
Nope, I do not know nor how to fix this, nor how to replicate.

**Comment by blackfed** [comment]
The thing is that it says the same thing when clicking on "Preferences" on your plugin... so it isn't a player issue like some people says, but I think it's a plugin issue.

**Comment by Cigaras** [comment]
Please provide the [plugins log file](https://github.com/Cigaras/IPTV.bundle#troubleshooting).
