### ISSUE TITLE
Plex turn off

### ISSUE THREAD

**Issue by haxcop** [Cigaras/IPTV.bundle#63]
Hi , Installing iptv on the latest pms V- when i try to play even the sample list it crash and shutdown the pms. 
I have tried many combinations but nothing seems to work even with a paid iptv list / url finishing on ts and also changing the ts to m3u8
Andy Ideas? 
Thanks!

**Comment by Cigaras** [comment]
Check the [logs](https://support.plex.tv/hc/en-us/articles/200250417-Plex-Media-Server-Log-Files), especialy the [com.plexapp.plugins.iptv.log](https://github.com/Cigaras/IPTV.bundle#troubleshooting) file.

**Comment by haxcop** [comment]
@Cigaras Hey, yes PMS was crashing don't really know the reasson. i will be testiing this week and let you know more in details.
