### ISSUE TITLE
MacOS PHT unable to select a stream

### ISSUE THREAD

**Issue by iTommix** [Cigaras/IPTV.bundle#66]
I’m using PMS and Plex HT on my Mac Mini with the Apple Remote. I cant select a channel either with my Apple Remote nor with keyboard. I am able to play a stream with the **Play-Button** or **Random-Button** on the left from the HT. Click on a channel does nothing.

**Comment by juliors** [comment]
Same problem here.

**Comment by Cigaras** [comment]
Do other channels works, like YouTube for example? I do not have and Mac Mini or Raspberry Pi to test, also Plex Home Theater app is pretty much abandoned, what about the new [Plex Media Player](https://www.plex.tv/downloads/)?

**Comment by Cigaras** [comment]
Some people reported same issue on [QNAP player](https://www.qnap.com/solution/plex-best-nas/en-us/) and looks like it is fixed in version [2.0.0](https://github.com/Cigaras/IPTV.bundle/tree/beta), so it kind of should work now.
