### ISSUE TITLE
Multiple Streams On Plex Server

### ISSUE THREAD

**Issue by brynthompson** [Cigaras/IPTV.bundle#67]
I have a PLEX server running the IPTV.Bundle and have an issue with multiple streams not working so say I have my iphone playing one channel Sky Sports 1 ( no problem ) and I try to watch a different or the same channel on my kitchen Now TV Box as soon as the second stream is selected the first will stop.
I can play and channel on and device no problem but as soon as two are attempted at the same time the first will fail.
The provider of the streams allows multiple streams to play I have 6 concurrent and they have confirmed its working so it must be a plex / IPTV.Bundle problem and ideas ?

**Comment by plexmediaserver** [comment]
if they are using extream codes for there IPTV. then thats were the problem is and xtreams codes with only let 1 HLS device connect at a time which now tv only supports

**Comment by brynthompson** [comment]
Oh my days your a genius I have spent weeks messing about with this to try and get it working lol

Right so if I use a different playlist type such as a standard m3u but still my same iptv provider using extream codes still will that resolve the problem or do I need to find another iptv provider ?

Kind Regards

Bryn Thompson
PC Solutions / Focus IT Ltd
01624 627171 / 01624 611222
www.pcsolutions.co.im<http://www.pcsolutions.co.im>

_____________________________

**Comment by plexmediaserver** [comment]
set it 0 if using hls if set to 10 it will only allow 1 connection 0 means inlimited
