### ISSUE TITLE
Sub-categories

### ISSUE THREAD

**Issue by weescotsman** [Cigaras/IPTV.bundle#68]
i am using this IPTV bundle and have my channels that i use, I am trying to organise so i have my usa folder with the usa channels in it, a uk folder with uk channels in it, Is this possible ????  At the moment i have CHANNELS > usa sports, usa movies, uk sports, uk movies  ect  .......    but i would like to have it as  this CHANNELS >   USA > usa sports, usa movies, usa series  ect 
                   >   UK > uk sports, uk movies, uk series ect

**Comment by Cigaras** [comment]
I will not do that.

Best I can suggest for the moment is to install this plugin [multiple times](https://github.com/Cigaras/IPTV.bundle/issues/21#issuecomment-159568329) for USA, UK and so on, and use dedicated playlists and groups for each.
