### ISSUE TITLE
Crashing Plex

### ISSUE THREAD

**Issue by Burn3rs** [Cigaras/IPTV.bundle#73]
I already tested the application on my Plex Server like 3 months ago and it was working fine, recently I wanted to try it to start adding some new links on it but no channels are working even after reinstalling the plugin. If I try to play the channels multiple times my Plex crash and is not connected anymore until I restart it.

Anyway to check logs to see what's happening?

Using Debian server and Web Plex player to test, Maybe a plex update broke something?

Plex Version 1.3.3.3148

**Comment by xplosionz** [comment]
I tested a local on Version 1.2.5.2966 and it works... 

Is it from the updates?

**Comment by Cigaras** [comment]
I can not reproduce this issue either, please give an example of a stream that does not work.
