### ISSUE TITLE
Force channel refresh from m3u

### ISSUE THREAD

**Issue by privatesam** [Cigaras/IPTV.bundle#77]
I'm using an external m3u (via http) I can't find a way for the plugin to force itself to refresh the list of channels or change the interval its checks the m3u?

**Comment by Cigaras** [comment]
Starting with version 2.0.0 playlist is reloaded every time You start the plug-in. I am not sure when Plex shuts down idle plug-ins so best bet would be just restarting the Plex server.

In addition plug-in check every minute if playlist file name was changed in preferences and if it was plug-in reloads the playlist in the background.

Also I implemented a daily playlist reload that can be set up in preferences:
![preferences](https://cloud.githubusercontent.com/assets/244432/23116962/0d3fa73a-f756-11e6-8e2c-7f5ece3065ce.png)
