### ISSUE TITLE
EPG strangeness

### ISSUE THREAD

**Issue by joeczucha** [Cigaras/IPTV.bundle#90]
Firstly, I just wanted to thank you for your work on this plugin.

I'm experiencing some strangeness with an EPG generated by WebGrab++.

With master (v2.0.0) I can't get the EPG data to display at all. Under each channel it just says "No description available". Has the EPG functionality changed with this version?

I then checked out v1.2.9 (as I was experiencing some different issues with 1.2.10) and it kind of works:

If I match the `channel` attribute to stream title then it displays the listing correctly under the channel. 

    #EXTINF:-1 tvg-ID="UK: alibi" tvg-name="UK : ALIBI" tvg-logo="http://mytv.com/logos/alibi.png" group-title="SKY UK ENTERTAINMENT",UK : ALIBI
    http://mytv.com/123.m3u8

    <tv generator-info-name="WebGrab+Plus/w MDB &amp; REX Postprocess -- version  V2.0 -- Jan van Straaten" generator-info-url="http://www.webgrabplus.com">
      <channel id="UK : ALIBI">
        <display-name lang="en">Alibi</display-name>
        <icon src="http://my.tvguide.co.uk/channel_logos/520.png" />
        <url>http://www.tvguide.co.uk</url>
      </channel>
      <programme start="20170301040000 +0000" stop="20170301070000 +0000" channel="UK : ALIBI">
        ...
      </programme>
    </tv>

But if I match the `channel` attribute to the `tvg-id` (as per the instructions) then it doesn't display.

    #EXTINF:-1 tvg-ID="UK: alibi" tvg-name="UK : ALIBI" tvg-logo="http://mytv.com/logos/alibi.png" group-title="SKY UK ENTERTAINMENT",UK : ALIBI
    http://mytv.com/123.m3u8

    <tv generator-info-name="WebGrab+Plus/w MDB &amp; REX Postprocess -- version  V2.0 -- Jan van Straaten" generator-info-url="http://www.webgrabplus.com">
      <channel id="UK: alibi">
        <display-name lang="en">Alibi</display-name>
        <icon src="http://my.tvguide.co.uk/channel_logos/520.png" />
        <url>http://www.tvguide.co.uk</url>
      </channel>
      <programme start="20170301040000 +0000" stop="20170301070000 +0000" channel="UK: alibi">
        ...
      </programme>
    </tv>

Using the `tvg-id` would be preferable as there are several channels (SD, HD, etc) which use the same `tvg-id` - but have different stream titles - so I'd like them to share the same channel data.

Thanks in advance.

**Comment by Cigaras** [comment]
Attributes in playlist are case sensitive, You have `tvg-ID`, should be `tvg-id`.

**Comment by joeczucha** [comment]
Great spot! That's fixed it on 1.2.9 but on the latest version I still get "No description available" under every channel 

(I'm not changing anything else, the only difference is switching between the Git branches)

Thanks for your help with this.

**Comment by Cigaras** [comment]
You need to reaload the playlist for changes to take effect, if You have automatic playlist update set to never in preferences just restart the PMS, otherwise delete file `...\Plex Media Server\Plug-in Support\Data\com.plexapp.plugins.iptv\Dict` while PMS is shut down, or just wait for it to reload by itself.

**Comment by joeczucha** [comment]
Yep, that did the trick 👍  Thanks again
