### ISSUE TITLE
#EXTINF with / in the group-title (or maybe tvg-name) crashes the channel

### ISSUE THREAD

**Issue by SprkFade** [Cigaras/IPTV.bundle#92]
If there's an #EXTINF with a / in the group-title (or maybe the tvg-name) it will crash the channel and it just says that the channel is not responding.

Example:
#EXTINF:-1 tvg-ID="USS: NBA TV HD" tvg-name="USA/CA: NBA TV HD" tvg-logo="http://www.lyngsat-logo.com/hires/nn/nba_tv_lam.png" group-title="USA/CA: Sports",USA/CA: NBA TV HD

**Comment by Cigaras** [comment]
Then don't use it, change it to , or | or something.
