### ISSUE TITLE
Nvidia Shield not working

### ISSUE THREAD

**Issue by teshiburu** [Cigaras/IPTV.bundle#93]
HI, 

I can get the IPTV working on web, and pmp. 

But im struggling with the Shield and Mobile devices, 

I have some remote log files from the shield but they contain private info - can i email them to you?

**Comment by Cigaras** [comment]
> remote log files from the shield
I am more interested in plug-ins logs from the server, but sure, You can email them to me.

However if it has no errors I won't be able to suggest anything else except what is already suggested in [Troubleshooting wiki](https://github.com/Cigaras/IPTV.bundle/wiki/Troubleshooting).

**Comment by RedManMark86** [comment]
Hi There,

Just to add that I also cannot get it to work with any Plex that is on an android device, yet Samsung TV's running Tizen will play everything beautifully

**Comment by RedManMark86** [comment]
Just to add a little extra to this.

My Samsung Galaxy S7 Edge wouldn't play any stream. Plex media server would show the request saying that it was direct playing but my phone would be forever on a spinning wheel.

So I started rolling backwards and amazingly version 1.2.10 works, nothing after it and nothing before it. Sadly though android boxes with plex still fail.

**Comment by Cigaras** [comment]
@RedManMark86 could You share one stream that works with version 1.2.10 but does not work with others? And version of Android You have on Your S7 Edge?
