### ISSUE TITLE
Non responsive channel v2.04

### ISSUE THREAD

**Issue by kanabrewski** [Cigaras/IPTV.bundle#97]
no luck on plex web, nor roku.
I reverted back to 2.03

**Comment by Cigaras** [comment]
Please give more details about this issue, what do You mean by saying non responsive?

**Comment by Cigaras** [comment]
Fixed in version [2.0.5](https://github.com/Cigaras/IPTV.bundle/releases)

**Comment by kanabrewski** [comment]
Thank you, that fixed it
