### ISSUE TITLE
Update m3u every 15 min?

### ISSUE THREAD

**Issue by skinnyzaz** [Cigaras/IPTV.bundle#99]
Is there a way to update the m3u say every 15 min. I change it manually but the m3u does not update with out restarting the server. I see the m3u refresh command only allows you to have the file refresh once a day.

**Comment by Cigaras** [comment]
I will add this in the future, but I am short on time at the moment so it might take a while.

**Comment by skinnyzaz** [comment]
If this plugin is updated I will be using it daily so I am more than happy to send a nice donation to get the plugin updated with this feature. Any chance that could speed things up? :)

**Comment by Cigaras** [comment]
I added a manual reload option in version [2.1.0](https://github.com/Cigaras/IPTV.bundle/releases), this should solve Your problem of not seeing changes every time You edit Your playlist, but will not unnecessary stress the system or servers every 15 min.

**Comment by skinnyzaz** [comment]
How is the manual reload triggered?

**Comment by skinnyzaz** [comment]
Great I think this will work nicely :) thanks a lot. Do you have a donation link?

**Comment by Cigaras** [comment]
Yes, it's at the top of [read me file](https://github.com/Cigaras/IPTV.bundle#plex-plug-in-that-plays-live-streams-like-iptv-from-a-m3u-playlist):

[![PayPal](https://img.shields.io/badge/donate-PayPal-green.svg)](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=Cigaras%40gmail%2ecom&lc=LT&currency_code=EUR&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted)
